import { PrimaryWordsInterface } from '../types/types';

export const wordsForAdverbsTests: PrimaryWordsInterface[] = [
  {
    valid: 'без оглядки',
    invalid: 'безоглядки',
    id: 0,
    trainerType: 'наречия',
  },
  {
    valid: 'без разбору',
    invalid: 'безразбору',
    id: 1,
    trainerType: 'наречия',
  },
  {
    valid: 'без спросу',
    invalid: 'безспросу',
    id: 2,
    trainerType: 'наречия',
  },
  {
    valid: 'без толку',
    invalid: 'безтолку',
    id: 3,
    trainerType: 'наречия',
  },
  {
    valid: 'без умолку',
    invalid: 'безумолку',
    id: 4,
    trainerType: 'наречия',
  },
  {
    valid: 'бок о бок',
    invalid: 'бок-о-бок',
    id: 5,
    trainerType: 'наречия',
  },
  {
    valid: 'в виде',
    invalid: 'ввиде',
    id: 6,
    trainerType: 'наречия',
  },
  {
    valid: 'в заключение',
    invalid: 'взаключение',
    id: 7,
    trainerType: 'наречия',
  },
  {
    valid: 'вне зависимости',
    invalid: 'внезависимости',
    id: 8,
    trainerType: 'наречия',
  },
  {
    valid: 'в обнимку',
    invalid: 'вобнимку',
    id: 9,
    trainerType: 'наречия',
  },
  {
    valid: 'в обтяжку',
    invalid: 'вобтяжку',
    id: 10,
    trainerType: 'наречия',
  },
  {
    valid: 'в общем',
    invalid: 'вобщем',
    id: 11,
    trainerType: 'наречия',
  },
  {
    valid: 'в одиночку',
    invalid: 'водиночку',
    id: 12,
    trainerType: 'наречия',
  },
  {
    valid: 'в открытую',
    invalid: 'воткрытую',
    id: 13,
    trainerType: 'наречия',
  },
  {
    valid: 'в потёмках',
    invalid: 'впотёмках',
    id: 14,
    trainerType: 'наречия',
  },
  {
    valid: 'в розницу',
    invalid: 'врозницу',
    id: 15,
    trainerType: 'наречия',
  },
  {
    valid: 'в сердцах',
    invalid: 'всердцах',
    id: 16,
    trainerType: 'наречия',
  },
  {
    valid: 'всё равно',
    invalid: 'всёравно',
    id: 17,
    trainerType: 'наречия',
  },
  {
    valid: 'в ходу',
    invalid: 'входу',
    id: 18,
    trainerType: 'наречия',
  },
  {
    valid: 'в упор',
    invalid: 'вупор',
    id: 19,
    trainerType: 'наречия',
  },
  {
    valid: 'в целом',
    invalid: 'вцелом',
    id: 20,
    trainerType: 'наречия',
  },
  {
    valid: 'за границей',
    invalid: 'заграницей',
    id: 21,
    trainerType: 'наречия',
  },
  {
    valid: 'за глаза',
    invalid: 'заглаза',
    id: 22,
    trainerType: 'наречия',
  },
  {
    valid: 'как будто',
    invalid: 'как-будто',
    id: 23,
    trainerType: 'наречия',
  },
  {
    valid: 'как раз',
    invalid: 'какраз',
    id: 24,
    trainerType: 'наречия',
  },
  {
    valid: 'к утру',
    invalid: 'кутру',
    id: 25,
    trainerType: 'наречия',
  },
  {
    valid: 'на бегу',
    invalid: 'набегу',
    id: 26,
    trainerType: 'наречия',
  },
  {
    valid: 'на вид',
    invalid: 'навид',
    id: 27,
    trainerType: 'наречия',
  },
  {
    valid: 'на глаз',
    invalid: 'наглаз',
    id: 28,
    trainerType: 'наречия',
  },
  {
    valid: 'на днях',
    invalid: 'наднях',
    id: 29,
    trainerType: 'наречия',
  },
  {
    valid: 'на миг',
    invalid: 'намиг',
    id: 30,
    trainerType: 'наречия',
  },
  {
    valid: 'на ощупь',
    invalid: 'наощупь',
    id: 31,
    trainerType: 'наречия',
  },
  {
    valid: 'на ходу',
    invalid: 'находу',
    id: 32,
    trainerType: 'наречия',
  },
  {
    valid: 'по двое',
    invalid: 'подвое',
    id: 33,
    trainerType: 'наречия',
  },
  {
    valid: 'по одному',
    invalid: 'по-одному',
    id: 34,
    trainerType: 'наречия',
  },
  {
    valid: 'с виду',
    invalid: 'свиду',
    id: 35,
    trainerType: 'наречия',
  },
  {
    valid: 'след в след',
    invalid: 'след-в-след',
    id: 36,
    trainerType: 'наречия',
  },
  {
    valid: 'с полуслова',
    invalid: 'сполуслова',
    id: 37,
    trainerType: 'наречия',
  },
  {
    valid: 'с разбегу',
    invalid: 'сразбегу',
    id: 38,
    trainerType: 'наречия',
  },
  {
    valid: 'с ходу',
    invalid: 'сходу',
    id: 39,
    trainerType: 'наречия',
  },
  {
    valid: 'вблизи',
    invalid: 'в близи',
    id: 40,
    trainerType: 'наречия',
  },
  {
    valid: ' вбок',
    invalid: 'в бок',
    id: 41,
    trainerType: 'наречия',
  },
  {
    valid: 'вброд',
    invalid: 'в брод',
    id: 42,
    trainerType: 'наречия',
  },
  {
    valid: 'вверх',
    invalid: 'в верх',
    id: 43,
    trainerType: 'наречия',
  },
  {
    valid: 'вглубь',
    invalid: 'в глубь',
    id: 44,
    trainerType: 'наречия',
  },
  {
    valid: 'вдалеке',
    invalid: ' в далеке',
    id: 45,
    trainerType: 'наречия',
  },
  {
    valid: 'вдали́',
    invalid: 'в дали́',
    id: 46,
    trainerType: 'наречия',
  },
  {
    valid: 'вдвое',
    invalid: 'в двое',
    id: 47,
    trainerType: 'наречия',
  },
  {
    valid: 'вдвоём',
    invalid: 'в двоём',
    id: 48,
    trainerType: 'наречия',
  },
  {
    valid: 'взаперти',
    invalid: 'в заперти',
    id: 49,
    trainerType: 'наречия',
  },
  {
    valid: 'вконец',
    invalid: 'в конец',
    id: 50,
    trainerType: 'наречия',
  },
  {
    valid: 'влево',
    invalid: 'в лево',
    id: 51,
    trainerType: 'наречия',
  },
  {
    valid: 'вничью',
    invalid: 'в ничью',
    id: 52,
    trainerType: 'наречия',
  },
  {
    valid: 'внутрь',
    invalid: 'внутрь',
    id: 53,
    trainerType: 'наречия',
  },
  {
    valid: 'во́время',
    invalid: 'во́ время',
    id: 54,
    trainerType: 'наречия',
  },
  {
    valid: 'во вре́мя',
    invalid: ' вовре́мя ',
    id: 55,
    trainerType: 'наречия',
  },
  {
    valid: 'вовсю',
    invalid: 'во всю',
    id: 56,
    trainerType: 'наречия',
  },
  {
    valid: 'воедино',
    invalid: 'во едино',
    id: 57,
    trainerType: 'наречия',
  },
  {
    valid: 'впервы́е',
    invalid: ' в первы́е ',
    id: 58,
    trainerType: 'наречия',
  },
  {
    valid: 'вперёд',
    invalid: 'в перёд',
    id: 59,
    trainerType: 'наречия',
  },
  {
    valid: 'вплотну́ю',
    invalid: 'в плотну́ю',
    id: 60,
    trainerType: 'наречия',
  },
  {
    valid: 'вполголоса',
    invalid: ' в пол голоса ',
    id: 61,
    trainerType: 'наречия',
  },
  {
    valid: 'вполоборота',
    invalid: ' в пол оборота ',
    id: 62,
    trainerType: 'наречия',
  },
  {
    valid: 'вполсилы',
    invalid: ' в пол силы ',
    id: 63,
    trainerType: 'наречия',
  },
  {
    valid: 'впоследствии',
    invalid: ' в последствии ',
    id: 64,
    trainerType: 'наречия',
  },
  {
    valid: 'впотьмах',
    invalid: ' впотьмах',
    id: 65,
    trainerType: 'наречия',
  },
  {
    valid: 'вправду',
    invalid: ' в правду ',
    id: 66,
    trainerType: 'наречия',
  },
  {
    valid: 'вправе',
    invalid: 'в праве',
    id: 67,
    trainerType: 'наречия',
  },
  {
    valid: 'вправо',
    invalid: 'в право',
    id: 68,
    trainerType: 'наречия',
  },
  {
    valid: 'впрочем',
    invalid: 'в прочем',
    id: 69,
    trainerType: 'наречия',
  },
  {
    valid: 'врассыпную',
    invalid: ' в рассыпную ',
    id: 70,
    trainerType: 'наречия',
  },
  {
    valid: 'врастяжку',
    invalid: ' в растяжку ',
    id: 71,
    trainerType: 'наречия',
  },
  {
    valid: 'всерьёз',
    invalid: ' в серьёз ',
    id: 72,
    trainerType: 'наречия',
  },
  {
    valid: 'всецело',
    invalid: 'все цело',
    id: 73,
    trainerType: 'наречия',
  },
  {
    valid: 'вскоре',
    invalid: 'в скоре',
    id: 74,
    trainerType: 'наречия',
  },
  {
    valid: 'вслед',
    invalid: 'в след',
    id: 75,
    trainerType: 'наречия',
  },
  {
    valid: ' всплошную',
    invalid: ' в сплошную',
    id: 76,
    trainerType: 'наречия',
  },
  {
    valid: 'втайне',
    invalid: 'в тайне',
    id: 77,
    trainerType: 'наречия',
  },
  {
    valid: 'втрое',
    invalid: 'в трое',
    id: 78,
    trainerType: 'наречия',
  },
  {
    valid: 'вширь',
    invalid: 'в ширь',
    id: 79,
    trainerType: 'наречия',
  },
  {
    valid: 'добела',
    invalid: 'до бела',
    id: 80,
    trainerType: 'наречия',
  },
  {
    valid: 'до́верху',
    invalid: 'до́ верху',
    id: 81,
    trainerType: 'наречия',
  },
  {
    valid: 'донельзя',
    invalid: 'до нельзя',
    id: 82,
    trainerType: 'наречия',
  },
  {
    valid: 'досуха',
    invalid: 'до суха',
    id: 83,
    trainerType: 'наречия',
  },
  {
    valid: 'досыта',
    invalid: 'до сыта',
    id: 84,
    trainerType: 'наречия',
  },
  {
    valid: 'дочиста',
    invalid: 'до чиста',
    id: 85,
    trainerType: 'наречия',
  },
  {
    valid: 'замуж',
    invalid: 'за муж',
    id: 86,
    trainerType: 'наречия',
  },
  {
    valid: 'не замужем',
    invalid: 'не за мужем',
    id: 87,
    trainerType: 'наречия',
  },
  {
    valid: 'заодно',
    invalid: 'за одно',
    id: 88,
    trainerType: 'наречия',
  },
  {
    valid: 'зачастую',
    invalid: 'за частую',
    id: 89,
    trainerType: 'наречия',
  },
  {
    valid: 'издавна',
    invalid: 'из давна',
    id: 90,
    trainerType: 'наречия',
  },
  {
    valid: 'издалека',
    invalid: 'из далека',
    id: 91,
    trainerType: 'наречия',
  },
  {
    valid: 'изнутри',
    invalid: 'изнутри',
    id: 92,
    trainerType: 'наречия',
  },
  {
    valid: 'итак',
    invalid: 'и так',
    id: 93,
    trainerType: 'наречия',
  },
  {
    valid: 'кверху',
    invalid: 'к верху',
    id: 94,
    trainerType: 'наречия',
  },
  {
    valid: 'кряду',
    invalid: 'к ряду',
    id: 95,
    trainerType: 'наречия',
  },
  {
    valid: 'на́двое',
    invalid: 'на́ двое',
    id: 96,
    trainerType: 'наречия',
  },
  {
    valid: 'наедине',
    invalid: 'на едине',
    id: 97,
    trainerType: 'наречия',
  },
  {
    valid: 'назавтра',
    invalid: 'на завтра',
    id: 98,
    trainerType: 'наречия',
  },
  {
    valid: 'напоказ',
    invalid: 'на показ',
    id: 99,
    trainerType: 'наречия',
  },
  {
    valid: 'назубок',
    invalid: 'на зубок',
    id: 100,
    trainerType: 'наречия',
  },
  {
    valid: 'назло',
    invalid: 'на зло',
    id: 101,
    trainerType: 'наречия',
  },
  {
    valid: 'на́смерть',
    invalid: 'на́ смерть',
    id: 102,
    trainerType: 'наречия',
  },
  {
    valid: 'насовсем',
    invalid: 'на совсем',
    id: 103,
    trainerType: 'наречия',
  },
  {
    valid: 'наспех',
    invalid: 'на спех',
    id: 104,
    trainerType: 'наречия',
  },
  {
    valid: 'наутро',
    invalid: 'на утро',
    id: 105,
    trainerType: 'наречия',
  },
  {
    valid: 'то́тчас',
    invalid: 'то́т час',
    id: 106,
    trainerType: 'наречия',
  },
  {
    valid: 'вмиг',
    invalid: 'в миг',
    id: 107,
    trainerType: 'наречия',
  },
  {
    valid: 'вширь',
    invalid: 'в ширь',
    id: 108,
    trainerType: 'наречия',
  },
];
