import { PrimaryWordsInterface } from '../types/types';

export const wordsForAccentsTests: PrimaryWordsInterface[] = [
  {
    valid: 'аэропОрты',
    invalid: 'аэропортЫ',
    id: 0,
    trainerType: 'ударения',
  },
  {
    valid: 'бАнты',
    invalid: 'бантЫ',
    id: 1,
    trainerType: 'ударения',
  },
  {
    valid: 'бухгАлтеров',
    invalid: 'бухгалтерОв',
    id: 2,
    trainerType: 'ударения',
  },
  {
    valid: 'вероисповЕдание',
    invalid: 'вероисповедАние',
    id: 3,
    trainerType: 'ударения',
  },
  {
    valid: 'водопровОд',
    invalid: 'водопрОвод',
    id: 4,
    trainerType: 'ударения',
  },
  {
    valid: 'дешевИзна',
    invalid: 'дешевизнА',
    id: 5,
    trainerType: 'ударения',
  },
  {
    valid: 'диспансЕр',
    invalid: 'диспАнсер',
    id: 6,
    trainerType: 'ударения',
  },
  {
    valid: 'досУг',
    invalid: 'дОсуг',
    id: 7,
    trainerType: 'ударения',
  },
  {
    valid: 'еретИк',
    invalid: 'ерЕтик',
    id: 8,
    trainerType: 'ударения',
  },
  {
    valid: 'жалюзИ',
    invalid: 'жАлюзи',
    id: 9,
    trainerType: 'ударения',
  },
  {
    valid: 'Иксы',
    invalid: 'иксЫ',
    id: 10,
    trainerType: 'ударения',
  },
  {
    valid: 'каталОг',
    invalid: 'катАлог',
    id: 11,
    trainerType: 'ударения',
  },
  {
    valid: 'квартАл',
    invalid: 'квАртал',
    trainerType: 'ударения',
    id: 12,
  },
  {
    valid: 'крАны',
    invalid: 'кранЫ',
    trainerType: 'ударения',
    id: 13,
  },
  {
    valid: 'кремЕнь',
    invalid: 'крЕмень',
    trainerType: 'ударения',
    id: 14,
  },
  {
    valid: 'кремнЯ',
    invalid: 'крЕмня',
    trainerType: 'ударения',
    id: 15,
  },
  {
    valid: 'лЕкторов',
    invalid: 'лекторОв',
    id: 16,
    trainerType: 'ударения',
  },
  {
    valid: 'лОктя',
    invalid: 'локтЯ',
    trainerType: 'ударения',
    id: 17,
  },
  {
    valid: 'локтЕй',
    invalid: 'лОктей',
    trainerType: 'ударения',
    id: 18,
  },
  {
    valid: 'намЕрение',
    invalid: 'немерЕние',
    id: 19,
    trainerType: 'ударения',
  },
  {
    valid: 'нефтепровОд',
    invalid: 'нефтепрОвод',
    id: 20,
    trainerType: 'ударения',
  },
  {
    valid: 'нОгтя',
    invalid: 'ногтЯ',
    id: 21,
    trainerType: 'ударения',
  },
  {
    valid: 'Отрочество',
    invalid: 'отрОчество',
    id: 22,
    trainerType: 'ударения',
  },
  {
    valid: 'партЕр',
    invalid: 'пАртер',
    id: 23,
    trainerType: 'ударения',
  },
  {
    valid: 'придАное',
    invalid: 'прИданое',
    id: 24,
    trainerType: 'ударения',
  },
  {
    valid: 'свЁкла',
    invalid: 'свеклА',
    id: 25,
    trainerType: 'ударения',
  },
  {
    valid: 'сирОты',
    invalid: 'сИроты',
    id: 26,
    trainerType: 'ударения',
  },
  {
    valid: 'сосредотОчение',
    invalid: 'сосредоточЕние',
    id: 27,
    trainerType: 'ударения',
  },
  {
    valid: 'срЕдства',
    invalid: 'средствА',
    id: 28,
    trainerType: 'ударения',
  },
  {
    valid: 'столЯр',
    invalid: 'стОляр',
    id: 29,
    trainerType: 'ударения',
  },
  {
    valid: 'тОрты',
    invalid: 'тортЫ',
    id: 30,
    trainerType: 'ударения',
  },
  {
    valid: 'тУфля',
    invalid: 'туфлЯ',
    id: 31,
    trainerType: 'ударения',
  },
  {
    valid: 'цемЕнт',
    invalid: 'цЕмент',
    id: 32,
    trainerType: 'ударения',
  },
  {
    valid: 'цепОчка',
    invalid: 'цЕпочка',
    id: 33,
    trainerType: 'ударения',
  },
  {
    valid: 'шАрфы',
    invalid: 'шарфЫ',
    id: 34,
    trainerType: 'ударения',
  },
  {
    valid: 'красИвее',
    invalid: 'красивЕе',
    id: 35,
    trainerType: 'ударения',
  },
  {
    valid: 'кУхонный',
    invalid: 'кухОнный',
    id: 36,
    trainerType: 'ударения',
  },
  {
    valid: 'мозаИчный',
    invalid: 'мозАичный',
    id: 37,
    trainerType: 'ударения',
  },
  {
    valid: 'оптОвый',
    invalid: 'Оптовый',
    id: 38,
    trainerType: 'ударения',
  },
  {
    valid: 'прозорлИвый',
    invalid: 'прозОрливый',
    id: 39,
    trainerType: 'ударения',
  },
  {
    valid: 'слИвовый',
    invalid: 'сливОвый',
    id: 40,
    trainerType: 'ударения',
  },
  {
    valid: 'бралА',
    invalid: 'брАла',
    id: 41,
    trainerType: 'ударения',
  },
  {
    valid: 'воссоздалА',
    invalid: 'воссоздАла',
    id: 42,
    trainerType: 'ударения',
  },
  {
    valid: 'влилАсь',
    invalid: 'влИлась',
    id: 43,
    trainerType: 'ударения',
  },
  {
    valid: 'вручИт',
    invalid: 'врУчит',
    id: 44,
    trainerType: 'ударения',
  },
  {
    valid: 'гналА',
    invalid: 'гнАла',
    id: 45,
    trainerType: 'ударения',
  },
  {
    valid: 'дозвонИтся',
    invalid: 'дозвОнится',
    id: 46,
    trainerType: 'ударения',
  },
  {
    valid: 'дозИровать',
    invalid: 'дозировАть',
    id: 47,
    trainerType: 'ударения',
  },
  {
    valid: 'закУпорить',
    invalid: 'закупОрить',
    id: 48,
    trainerType: 'ударения',
  },
  {
    valid: 'зАнял',
    invalid: 'занЯл',
    id: 49,
    trainerType: 'ударения',
  },
  {
    valid: 'занялА',
    invalid: 'зАняла',
    id: 50,
    trainerType: 'ударения',
  },
  {
    valid: 'зАняли',
    invalid: 'занЯли',
    id: 51,
    trainerType: 'ударения',
  },
  {
    valid: 'заперлА',
    invalid: 'зАперла',
    id: 52,
    trainerType: 'ударения',
  },
  {
    valid: 'запломбировАть',
    invalid: 'запломбИровать',
    id: 53,
    trainerType: 'ударения',
  },
  {
    valid: 'защемИт',
    invalid: 'защЕмит',
    id: 54,
    trainerType: 'ударения',
  },
  {
    valid: 'звонИт',
    invalid: 'звОнит',
    id: 55,
    trainerType: 'ударения',
  },
  {
    valid: 'кАшлянуть',
    invalid: 'кашлянУть',
    id: 56,
    trainerType: 'ударения',
  },
  {
    valid: 'клАла',
    invalid: 'клалА',
    id: 57,
    trainerType: 'ударения',
  },
  {
    valid: 'крАлась',
    invalid: 'кралАсь',
    id: 58,
    trainerType: 'ударения',
  },
  {
    valid: 'кровоточИть',
    invalid: 'кровотОчить',
    id: 59,
    trainerType: 'ударения',
  },
  {
    valid: 'лгалА',
    invalid: 'лгАла',
    id: 60,
    trainerType: 'ударения',
  },
  {
    valid: 'лилА',
    invalid: 'лИла',
    id: 61,
    trainerType: 'ударения',
  },
  {
    valid: 'навралА',
    invalid: 'наврАла',
    id: 62,
    trainerType: 'ударения',
  },
  {
    valid: 'наделИт',
    invalid: 'надЕлит',
    id: 63,
    trainerType: 'ударения',
  },
  {
    valid: 'накренИтся',
    invalid: 'накрЕнится',
    id: 64,
    trainerType: 'ударения',
  },
  {
    valid: 'облегчИть',
    invalid: 'облЕгчить',
    id: 65,
    trainerType: 'ударения',
  },
  {
    valid: 'одолжИт',
    invalid: 'одОлжит',
    id: 66,
    trainerType: 'ударения',
  },
  {
    valid: 'озлОбить',
    invalid: 'озлобИть',
    id: 67,
    trainerType: 'ударения',
  },
  {
    valid: 'окружИт',
    invalid: 'окрУжит',
    id: 68,
    trainerType: 'ударения',
  },
  {
    valid: 'опОшлить',
    invalid: 'опошлИть',
    id: 69,
    trainerType: 'ударения',
  },
  {
    valid: 'освЕдомиться',
    invalid: 'осведомИться',
    id: 70,
    trainerType: 'ударения',
  },
  {
    valid: 'откУпорить',
    invalid: 'откупОрить',
    id: 71,
    trainerType: 'ударения',
  },
  {
    valid: 'пломбировАть',
    invalid: 'пломбИровать',
    id: 72,
    trainerType: 'ударения',
  },
  {
    valid: 'послАла',
    invalid: 'послалА',
    id: 73,
    trainerType: 'ударения',
  },
  {
    valid: 'прИбыл',
    invalid: 'прибЫл',
    id: 74,
    trainerType: 'ударения',
  },
  {
    valid: 'сверлИт',
    invalid: 'свЕрлит',
    id: 75,
    trainerType: 'ударения',
  },
  {
    valid: 'сорИт',
    invalid: 'сОрит',
    id: 76,
    trainerType: 'ударения',
  },
  {
    valid: 'углубИть',
    invalid: 'углУбить',
    id: 77,
    trainerType: 'ударения',
  },
  {
    valid: 'чЕрпать',
    invalid: 'черпАть',
    id: 78,
    trainerType: 'ударения',
  },
  {
    valid: 'щемИт',
    invalid: 'щЕмит',
    id: 79,
    trainerType: 'ударения',
  },
  {
    valid: 'щЁлкать',
    invalid: 'щелкАть',
    id: 80,
    trainerType: 'ударения',
  },
  {
    valid: 'зАгнутый',
    invalid: 'загнУтый',
    id: 81,
    trainerType: 'ударения',
  },
  {
    valid: 'занятА',
    invalid: 'зАнята',
    id: 82,
    trainerType: 'ударения',
  },
  {
    valid: 'зАпертый',
    invalid: 'запЁртый',
    id: 83,
    trainerType: 'ударения',
  },
  {
    valid: 'кормЯщий',
    invalid: 'кОрмящий',
    id: 84,
    trainerType: 'ударения',
  },
  {
    valid: 'кровоточАщий',
    invalid: 'кровотОчащий',
    id: 85,
    trainerType: 'ударения',
  },
  {
    valid: 'нажИвший',
    invalid: 'нАживший',
    id: 86,
    trainerType: 'ударения',
  },
  {
    valid: 'нанЯвшийся',
    invalid: 'нАнявшийся',
    id: 87,
    trainerType: 'ударения',
  },
  {
    valid: 'начАвший',
    invalid: 'нАчавший',
    id: 88,
    trainerType: 'ударения',
  },
  {
    valid: 'нАчатый',
    invalid: 'начАтый',
    id: 89,
    trainerType: 'ударения',
  },
  {
    valid: 'низведЁнный',
    invalid: 'низвЕденный',
    id: 90,
    trainerType: 'ударения',
  },
  {
    valid: 'облегчЁнный',
    invalid: 'облЕгченный',
    id: 91,
    trainerType: 'ударения',
  },
  {
    valid: 'ободрЁнный',
    invalid: 'обОдренный',
    id: 92,
    trainerType: 'ударения',
  },
  {
    valid: 'обострЁнный',
    invalid: 'обОстренный',
    id: 93,
    trainerType: 'ударения',
  },
  {
    valid: 'отключЁнный',
    invalid: 'отклЮченный',
    id: 94,
    trainerType: 'ударения',
  },
  {
    valid: 'поделЁнный',
    invalid: 'подЕленный',
    id: 95,
    trainerType: 'ударения',
  },
  {
    valid: 'понЯвший',
    invalid: 'пОнявший',
    id: 96,
    trainerType: 'ударения',
  },
  {
    valid: 'принятА',
    invalid: 'прИнята',
    id: 97,
    trainerType: 'ударения',
  },
  {
    valid: 'приручЁнный',
    invalid: 'прирУченный',
    id: 98,
    trainerType: 'ударения',
  },
  {
    valid: 'прожИвший',
    invalid: 'прОживший',
    id: 99,
    trainerType: 'ударения',
  },
  {
    valid: 'снятА',
    invalid: 'снЯта',
    id: 100,
    trainerType: 'ударения',
  },
  {
    valid: 'сОгнутый',
    invalid: 'согнУтый',
    id: 101,
    trainerType: 'ударения',
  },
  {
    valid: 'углублЁнный',
    invalid: 'углУбленный',
    id: 102,
    trainerType: 'ударения',
  },
  {
    valid: 'закУпорив',
    invalid: 'закупОрив',
    id: 103,
    trainerType: 'ударения',
  },
  {
    valid: 'начАв',
    invalid: 'нАчав',
    id: 104,
    trainerType: 'ударения',
  },
  {
    valid: 'начАвшись',
    invalid: 'нАчавшись',
    id: 105,
    trainerType: 'ударения',
  },
  {
    valid: 'поднЯв',
    invalid: 'пОдняв',
    id: 106,
    trainerType: 'ударения',
  },
  {
    valid: 'прибЫв',
    invalid: 'прИбыв',
    id: 107,
    trainerType: 'ударения',
  },
  {
    valid: 'дОверху',
    invalid: 'довЕрху',
    id: 108,
    trainerType: 'ударения',
  },
  {
    valid: 'донЕльзя',
    invalid: 'дОнельзя',
    id: 109,
    trainerType: 'ударения',
  },
  {
    valid: 'дОнизу',
    invalid: 'донИзу',
    id: 110,
    trainerType: 'ударения',
  },
  {
    valid: 'дОсуха',
    invalid: 'досУха',
    id: 111,
    trainerType: 'ударения',
  },
  {
    valid: 'красИвее',
    invalid: 'красивЕе',
    id: 112,
    trainerType: 'ударения',
  },
];
