import { WordsForTrainers } from '../types/types';

export const wordsForTrainers: WordsForTrainers = {
  Ударения: {
    type: 'primary',
    inHeader: true,

    items: [
      {
        valid: 'аэропОрты',
        invalid: 'аэропортЫ',
        id: 0,
      },
      {
        valid: 'бАнты',
        invalid: 'бантЫ',
        id: 1,
      },
      {
        valid: 'бухгАлтеров',
        invalid: 'бухгалтерОв',
        id: 2,
      },
      {
        valid: 'вероисповЕдание',
        invalid: 'вероисповедАние',
        id: 3,
      },
      {
        valid: 'водопровОд',
        invalid: 'водопрОвод',
        id: 4,
      },
      {
        valid: 'дешевИзна',
        invalid: 'дешевизнА',
        id: 5,
      },
      {
        valid: 'диспансЕр',
        invalid: 'диспАнсер',
        id: 6,
      },
      {
        valid: 'досУг',
        invalid: 'дОсуг',
        id: 7,
      },
      {
        valid: 'еретИк',
        invalid: 'ерЕтик',
        id: 8,
      },
      {
        valid: 'жалюзИ',
        invalid: 'жАлюзи',
        id: 9,
      },
      {
        valid: 'Иксы',
        invalid: 'иксЫ',
        id: 10,
      },
      {
        valid: 'каталОг',
        invalid: 'катАлог',
        id: 11,
      },
      {
        valid: 'квартАл',
        invalid: 'квАртал',
        id: 12,
      },
      {
        valid: 'крАны',
        invalid: 'кранЫ',
        id: 13,
      },
      {
        valid: 'кремЕнь',
        invalid: 'крЕмень',
        id: 14,
      },
      {
        valid: 'кремнЯ',
        invalid: 'крЕмня',
        id: 15,
      },
      {
        valid: 'лЕкторов',
        invalid: 'лекторОв',
        id: 16,
      },
      {
        valid: 'лОктя',
        invalid: 'локтЯ',
        id: 17,
      },
      {
        valid: 'локтЕй',
        invalid: 'лОктей',
        id: 18,
      },
      {
        valid: 'намЕрение',
        invalid: 'немерЕние',
        id: 19,
      },
      {
        valid: 'нефтепровОд',
        invalid: 'нефтепрОвод',
        id: 20,
      },
      {
        valid: 'нОгтя',
        invalid: 'ногтЯ',
        id: 21,
      },
      {
        valid: 'Отрочество',
        invalid: 'отрОчество',
        id: 22,
      },
      {
        valid: 'партЕр',
        invalid: 'пАртер',
        id: 23,
      },
      {
        valid: 'придАное',
        invalid: 'прИданое',
        id: 24,
      },
      {
        valid: 'свЁкла',
        invalid: 'свеклА',
        id: 25,
      },
      {
        valid: 'сирОты',
        invalid: 'сИроты',
        id: 26,
      },
      {
        valid: 'сосредотОчение',
        invalid: 'сосредоточЕние',
        id: 27,
      },
      {
        valid: 'срЕдства',
        invalid: 'средствА',
        id: 28,
      },
      {
        valid: 'столЯр',
        invalid: 'стОляр',
        id: 29,
      },
      {
        valid: 'тОрты',
        invalid: 'тортЫ',
        id: 30,
      },
      {
        valid: 'тУфля',
        invalid: 'туфлЯ',
        id: 31,
      },
      {
        valid: 'цемЕнт',
        invalid: 'цЕмент',
        id: 32,
      },
      {
        valid: 'цепОчка',
        invalid: 'цЕпочка',
        id: 33,
      },
      {
        valid: 'шАрфы',
        invalid: 'шарфЫ',
        id: 34,
      },
      {
        valid: 'красИвее',
        invalid: 'красивЕе',
        id: 35,
      },
      {
        valid: 'кУхонный',
        invalid: 'кухОнный',
        id: 36,
      },
      {
        valid: 'мозаИчный',
        invalid: 'мозАичный',
        id: 37,
      },
      {
        valid: 'оптОвый',
        invalid: 'Оптовый',
        id: 38,
      },
      {
        valid: 'прозорлИвый',
        invalid: 'прозОрливый',
        id: 39,
      },
      {
        valid: 'слИвовый',
        invalid: 'сливОвый',
        id: 40,
      },
      {
        valid: 'бралА',
        invalid: 'брАла',
        id: 41,
      },
      {
        valid: 'воссоздалА',
        invalid: 'воссоздАла',
        id: 42,
      },
      {
        valid: 'влилАсь',
        invalid: 'влИлась',
        id: 43,
      },
      {
        valid: 'вручИт',
        invalid: 'врУчит',
        id: 44,
      },
      {
        valid: 'гналА',
        invalid: 'гнАла',
        id: 45,
      },
      {
        valid: 'дозвонИтся',
        invalid: 'дозвОнится',
        id: 46,
      },
      {
        valid: 'дозИровать',
        invalid: 'дозировАть',
        id: 47,
      },
      {
        valid: 'закУпорить',
        invalid: 'закупОрить',
        id: 48,
      },
      {
        valid: 'зАнял',
        invalid: 'занЯл',
        id: 49,
      },
      {
        valid: 'занялА',
        invalid: 'зАняла',
        id: 50,
      },
      {
        valid: 'зАняли',
        invalid: 'занЯли',
        id: 51,
      },
      {
        valid: 'заперлА',
        invalid: 'зАперла',
        id: 52,
      },
      {
        valid: 'запломбировАть',
        invalid: 'запломбИровать',
        id: 53,
      },
      {
        valid: 'защемИт',
        invalid: 'защЕмит',
        id: 54,
      },
      {
        valid: 'звонИт',
        invalid: 'звОнит',
        id: 55,
      },
      {
        valid: 'кАшлянуть',
        invalid: 'кашлянУть',
        id: 56,
      },
      {
        valid: 'клАла',
        invalid: 'клалА',
        id: 57,
      },
      {
        valid: 'крАлась',
        invalid: 'кралАсь',
        id: 58,
      },
      {
        valid: 'кровоточИть',
        invalid: 'кровотОчить',
        id: 59,
      },
      {
        valid: 'лгалА',
        invalid: 'лгАла',
        id: 60,
      },
      {
        valid: 'лилА',
        invalid: 'лИла',
        id: 61,
      },
      {
        valid: 'навралА',
        invalid: 'наврАла',
        id: 62,
      },
      {
        valid: 'наделИт',
        invalid: 'надЕлит',
        id: 63,
      },
      {
        valid: 'накренИтся',
        invalid: 'накрЕнится',
        id: 64,
      },
      {
        valid: 'облегчИть',
        invalid: 'облЕгчить',
        id: 65,
      },
      {
        valid: 'одолжИт',
        invalid: 'одОлжит',
        id: 66,
      },
      {
        valid: 'озлОбить',
        invalid: 'озлобИть',
        id: 67,
      },
      {
        valid: 'окружИт',
        invalid: 'окрУжит',
        id: 68,
      },
      {
        valid: 'опОшлить',
        invalid: 'опошлИть',
        id: 69,
      },
      {
        valid: 'освЕдомиться',
        invalid: 'осведомИться',
        id: 70,
      },
      {
        valid: 'откУпорить',
        invalid: 'откупОрить',
        id: 71,
      },
      {
        valid: 'пломбировАть',
        invalid: 'пломбИровать',
        id: 72,
      },
      {
        valid: 'послАла',
        invalid: 'послалА',
        id: 73,
      },
      {
        valid: 'прИбыл',
        invalid: 'прибЫл',
        id: 74,
      },
      {
        valid: 'сверлИт',
        invalid: 'свЕрлит',
        id: 75,
      },
      {
        valid: 'сорИт',
        invalid: 'сОрит',
        id: 76,
      },
      {
        valid: 'углубИть',
        invalid: 'углУбить',
        id: 77,
      },
      {
        valid: 'чЕрпать',
        invalid: 'черпАть',
        id: 78,
      },
      {
        valid: 'щемИт',
        invalid: 'щЕмит',
        id: 79,
      },
      {
        valid: 'щЁлкать',
        invalid: 'щелкАть',
        id: 80,
      },
      {
        valid: 'зАгнутый',
        invalid: 'загнУтый',
        id: 81,
      },
      {
        valid: 'занятА',
        invalid: 'зАнята',
        id: 82,
      },
      {
        valid: 'зАпертый',
        invalid: 'запЁртый',
        id: 83,
      },
      {
        valid: 'кормЯщий',
        invalid: 'кОрмящий',
        id: 84,
      },
      {
        valid: 'кровоточАщий',
        invalid: 'кровотОчащий',
        id: 85,
      },
      {
        valid: 'нажИвший',
        invalid: 'нАживший',
        id: 86,
      },
      {
        valid: 'нанЯвшийся',
        invalid: 'нАнявшийся',
        id: 87,
      },
      {
        valid: 'начАвший',
        invalid: 'нАчавший',
        id: 88,
      },
      {
        valid: 'нАчатый',
        invalid: 'начАтый',
        id: 89,
      },
      {
        valid: 'низведЁнный',
        invalid: 'низвЕденный',
        id: 90,
      },
      {
        valid: 'облегчЁнный',
        invalid: 'облЕгченный',
        id: 91,
      },
      {
        valid: 'ободрЁнный',
        invalid: 'обОдренный',
        id: 92,
      },
      {
        valid: 'обострЁнный',
        invalid: 'обОстренный',
        id: 93,
      },
      {
        valid: 'отключЁнный',
        invalid: 'отклЮченный',
        id: 94,
      },
      {
        valid: 'поделЁнный',
        invalid: 'подЕленный',
        id: 95,
      },
      {
        valid: 'понЯвший',
        invalid: 'пОнявший',
        id: 96,
      },
      {
        valid: 'принятА',
        invalid: 'прИнята',
        id: 97,
      },
      {
        valid: 'приручЁнный',
        invalid: 'прирУченный',
        id: 98,
      },
      {
        valid: 'прожИвший',
        invalid: 'прОживший',
        id: 99,
      },
      {
        valid: 'снятА',
        invalid: 'снЯта',
        id: 100,
      },
      {
        valid: 'сОгнутый',
        invalid: 'согнУтый',
        id: 101,
      },
      {
        valid: 'углублЁнный',
        invalid: 'углУбленный',
        id: 102,
      },
      {
        valid: 'закУпорив',
        invalid: 'закупОрив',
        id: 103,
      },
      {
        valid: 'начАв',
        invalid: 'нАчав',
        id: 104,
      },
      {
        valid: 'начАвшись',
        invalid: 'нАчавшись',
        id: 105,
      },
      {
        valid: 'поднЯв',
        invalid: 'пОдняв',
        id: 106,
      },
      {
        valid: 'прибЫв',
        invalid: 'прИбыв',
        id: 107,
      },
      {
        valid: 'дОверху',
        invalid: 'довЕрху',
        id: 108,
      },
      {
        valid: 'донЕльзя',
        invalid: 'дОнельзя',
        id: 109,
      },
      {
        valid: 'дОнизу',
        invalid: 'донИзу',
        id: 110,
      },
      {
        valid: 'дОсуха',
        invalid: 'досУха',
        id: 111,
      },
      {
        valid: 'красИвее',
        invalid: 'красивЕе',
        id: 112,
      },
    ],
  },

  Наречия: {
    type: 'primary',
    inHeader: true,

    items: [
      {
        valid: 'без оглядки',
        invalid: 'безоглядки',
        id: 0,
      },
      {
        valid: 'без разбору',
        invalid: 'безразбору',
        id: 1,
      },
      {
        valid: 'без спросу',
        invalid: 'безспросу',
        id: 2,
      },
      {
        valid: 'без толку',
        invalid: 'безтолку',
        id: 3,
      },
      {
        valid: 'без умолку',
        invalid: 'безумолку',
        id: 4,
      },
      {
        valid: 'бок о бок',
        invalid: 'бок-о-бок',
        id: 5,
      },
      {
        valid: 'в виде',
        invalid: 'ввиде',
        id: 6,
      },
      {
        valid: 'в заключение',
        invalid: 'взаключение',
        id: 7,
      },
      {
        valid: 'вне зависимости',
        invalid: 'внезависимости',
        id: 8,
      },
      {
        valid: 'в обнимку',
        invalid: 'вобнимку',
        id: 9,
      },
      {
        valid: 'в обтяжку',
        invalid: 'вобтяжку',
        id: 10,
      },
      {
        valid: 'в общем',
        invalid: 'вобщем',
        id: 11,
      },
      {
        valid: 'в одиночку',
        invalid: 'водиночку',
        id: 12,
      },
      {
        valid: 'в открытую',
        invalid: 'воткрытую',
        id: 13,
      },
      {
        valid: 'в потёмках',
        invalid: 'впотёмках',
        id: 14,
      },
      {
        valid: 'в розницу',
        invalid: 'врозницу',
        id: 15,
      },
      {
        valid: 'в сердцах',
        invalid: 'всердцах',
        id: 16,
      },
      {
        valid: 'всё равно',
        invalid: 'всёравно',
        id: 17,
      },
      {
        valid: 'в ходу',
        invalid: 'входу',
        id: 18,
      },
      {
        valid: 'в упор',
        invalid: 'вупор',
        id: 19,
      },
      {
        valid: 'в целом',
        invalid: 'вцелом',
        id: 20,
      },
      {
        valid: 'за границей',
        invalid: 'заграницей',
        id: 21,
      },
      {
        valid: 'за глаза',
        invalid: 'заглаза',
        id: 22,
      },
      {
        valid: 'как будто',
        invalid: 'как-будто',
        id: 23,
      },
      {
        valid: 'как раз',
        invalid: 'какраз',
        id: 24,
      },
      {
        valid: 'к утру',
        invalid: 'кутру',
        id: 25,
      },
      {
        valid: 'на бегу',
        invalid: 'набегу',
        id: 26,
      },
      {
        valid: 'на вид',
        invalid: 'навид',
        id: 27,
      },
      {
        valid: 'на глаз',
        invalid: 'наглаз',
        id: 28,
      },
      {
        valid: 'на днях',
        invalid: 'наднях',
        id: 29,
      },
      {
        valid: 'на миг',
        invalid: 'намиг',
        id: 30,
      },
      {
        valid: 'на ощупь',
        invalid: 'наощупь',
        id: 31,
      },
      {
        valid: 'на ходу',
        invalid: 'находу',
        id: 32,
      },
      {
        valid: 'по двое',
        invalid: 'подвое',
        id: 33,
      },
      {
        valid: 'по одному',
        invalid: 'по-одному',
        id: 34,
      },
      {
        valid: 'с виду',
        invalid: 'свиду',
        id: 35,
      },
      {
        valid: 'след в след',
        invalid: 'след-в-след',
        id: 36,
      },
      {
        valid: 'с полуслова',
        invalid: 'сполуслова',
        id: 37,
      },
      {
        valid: 'с разбегу',
        invalid: 'сразбегу',
        id: 38,
      },
      {
        valid: 'с ходу',
        invalid: 'сходу',
        id: 39,
      },
      {
        valid: 'вблизи',
        invalid: 'в близи',
        id: 40,
      },
      {
        valid: 'вбок',
        invalid: 'в бок',
        id: 41,
      },
      {
        valid: 'вброд',
        invalid: 'в брод',
        id: 42,
      },
      {
        valid: 'вверх',
        invalid: 'в верх',
        id: 43,
      },
      {
        valid: 'вглубь',
        invalid: 'в глубь',
        id: 44,
      },
      {
        valid: 'вдалеке',
        invalid: 'в далеке',
        id: 45,
      },
      {
        valid: 'вдали́',
        invalid: 'в дали́',
        id: 46,
      },
      {
        valid: 'вдвое',
        invalid: 'в двое',
        id: 47,
      },
      {
        valid: 'вдвоём',
        invalid: 'в двоём',
        id: 48,
      },
      {
        valid: 'взаперти',
        invalid: 'в заперти',
        id: 49,
      },
      {
        valid: 'вконец',
        invalid: 'в конец',
        id: 50,
      },
      {
        valid: 'влево',
        invalid: 'в лево',
        id: 51,
      },
      {
        valid: 'вничью',
        invalid: 'в ничью',
        id: 52,
      },
      {
        valid: 'внутрь',
        invalid: 'в нутрь',
        id: 53,
      },
      {
        valid: 'во́время',
        invalid: 'во́ время',
        id: 54,
      },
      {
        valid: 'во вре́мя',
        invalid: 'вовре́мя',
        id: 55,
      },
      {
        valid: 'вовсю',
        invalid: 'во всю',
        id: 56,
      },
      {
        valid: 'воедино',
        invalid: 'во едино',
        id: 57,
      },
      {
        valid: 'впервы́е',
        invalid: 'в первы́е',
        id: 58,
      },
      {
        valid: 'вперёд',
        invalid: 'в перёд',
        id: 59,
      },
      {
        valid: 'вплотну́ю',
        invalid: 'в плотну́ю',
        id: 60,
      },
      {
        valid: 'вполголоса',
        invalid: 'в пол голоса',
        id: 61,
      },
      {
        valid: 'вполоборота',
        invalid: 'в пол оборота',
        id: 62,
      },
      {
        valid: 'вполсилы',
        invalid: 'в пол силы',
        id: 63,
      },
      {
        valid: 'впоследствии',
        invalid: 'в последствии',
        id: 64,
      },
      {
        valid: 'впотьмах',
        invalid: 'в потьмах',
        id: 65,
      },
      {
        valid: 'вправду',
        invalid: 'в правду',
        id: 66,
      },
      {
        valid: 'вправе',
        invalid: 'в праве',
        id: 67,
      },
      {
        valid: 'вправо',
        invalid: 'в право',
        id: 68,
      },
      {
        valid: 'впрочем',
        invalid: 'в прочем',
        id: 69,
      },
      {
        valid: 'врассыпную',
        invalid: 'в рассыпную',
        id: 70,
      },
      {
        valid: 'врастяжку',
        invalid: 'в растяжку',
        id: 71,
      },
      {
        valid: 'всерьёз',
        invalid: 'в серьёз',
        id: 72,
      },
      {
        valid: 'всецело',
        invalid: 'все цело',
        id: 73,
      },
      {
        valid: 'вскоре',
        invalid: 'в скоре',
        id: 74,
      },
      {
        valid: 'вслед',
        invalid: 'в след',
        id: 75,
      },
      {
        valid: 'всплошную',
        invalid: 'в сплошную',
        id: 76,
      },
      {
        valid: 'втайне',
        invalid: 'в тайне',
        id: 77,
      },
      {
        valid: 'втрое',
        invalid: 'в трое',
        id: 78,
      },
      {
        valid: 'вширь',
        invalid: 'в ширь',
        id: 79,
      },
      {
        valid: 'добела',
        invalid: 'до бела',
        id: 80,
      },
      {
        valid: 'до́верху',
        invalid: 'до́ верху',
        id: 81,
      },
      {
        valid: 'донельзя',
        invalid: 'до нельзя',
        id: 82,
      },
      {
        valid: 'досуха',
        invalid: 'до суха',
        id: 83,
      },
      {
        valid: 'досыта',
        invalid: 'до сыта',
        id: 84,
      },
      {
        valid: 'дочиста',
        invalid: 'до чиста',
        id: 85,
      },
      {
        valid: 'замуж',
        invalid: 'за муж',
        id: 86,
      },
      {
        valid: 'не замужем',
        invalid: 'не за мужем',
        id: 87,
      },
      {
        valid: 'заодно',
        invalid: 'за одно',
        id: 88,
      },
      {
        valid: 'зачастую',
        invalid: 'за частую',
        id: 89,
      },
      {
        valid: 'издавна',
        invalid: 'из давна',
        id: 90,
      },
      {
        valid: 'издалека',
        invalid: 'из далека',
        id: 91,
      },
      {
        valid: 'изнутри',
        invalid: 'из нутри',
        id: 92,
      },
      {
        valid: 'итак',
        invalid: 'и так',
        id: 93,
      },
      {
        valid: 'кверху',
        invalid: 'к верху',
        id: 94,
      },
      {
        valid: 'кряду',
        invalid: 'к ряду',
        id: 95,
      },
      {
        valid: 'на́двое',
        invalid: 'на́ двое',
        id: 96,
      },
      {
        valid: 'наедине',
        invalid: 'на едине',
        id: 97,
      },
      {
        valid: 'назавтра',
        invalid: 'на завтра',
        id: 98,
      },
      {
        valid: 'напоказ',
        invalid: 'на показ',
        id: 99,
      },
      {
        valid: 'назубок',
        invalid: 'на зубок',
        id: 100,
      },
      {
        valid: 'назло',
        invalid: 'на зло',
        id: 101,
      },
      {
        valid: 'на́смерть',
        invalid: 'на́ смерть',
        id: 102,
      },
      {
        valid: 'насовсем',
        invalid: 'на совсем',
        id: 103,
      },
      {
        valid: 'наспех',
        invalid: 'на спех',
        id: 104,
      },
      {
        valid: 'наутро',
        invalid: 'на утро',
        id: 105,
      },
      {
        valid: 'то́тчас',
        invalid: 'то́т час',
        id: 106,
      },
      {
        valid: 'вмиг',
        invalid: 'в миг',
        id: 107,
      },
      {
        valid: 'вширь',
        invalid: 'в ширь',
        id: 108,
      },
    ],
  },

  'Словарные слова': {
    type: 'primary',
    inHeader: true,

    items: [
      {
        valid: 'тишина',
        invalid: 'тишена',
        differenceIndexes: [4],
        id: 0,
      },
      {
        valid: 'белизна',
        invalid: 'белезна',
        differenceIndexes: [4],
        id: 1,
      },
      {
        valid: 'празднество',
        invalid: 'праздненство',
        differenceIndexes: [7],
        id: 2,
      },
      {
        valid: 'маета',
        invalid: 'маята',
        differenceIndexes: [3],
        id: 3,
      },
      {
        valid: 'котловина',
        invalid: 'котлавина',
        differenceIndexes: [5],
        id: 4,
      },
      {
        valid: 'сердцевина',
        invalid: 'сердцивина',
        differenceIndexes: [6],
        id: 5,
      },
      {
        valid: 'взимать',
        invalid: 'взымать',
        differenceIndexes: [3],
        id: 6,
      },
      {
        valid: 'фельдъегерь',
        invalid: 'фельдьегерь',
        differenceIndexes: [6],
        id: 7,
      },
      {
        valid: 'преступление',
        invalid: 'приступление',
        differenceIndexes: [3],
        id: 8,
      },
      {
        valid: 'пресечь',
        invalid: 'присечь',
        differenceIndexes: [3],
        id: 9,
      },
      {
        valid: 'адъютант',
        invalid: 'адьютант',
        differenceIndexes: [3],
        id: 10,
      },
      {
        valid: 'пригарь',
        invalid: 'пригорь',
        differenceIndexes: [5],
        id: 11,
      },
      {
        valid: 'выгарки',
        invalid: 'выгорки',
        differenceIndexes: [4],
        id: 12,
      },
      {
        valid: 'изгарь',
        invalid: 'изгорь',
        differenceIndexes: [4],
        id: 13,
      },
      {
        valid: 'зоревать',
        invalid: 'заревать',
        differenceIndexes: [2],
        id: 14,
      },
      {
        valid: 'пловец',
        invalid: 'плавец',
        differenceIndexes: [3],
        id: 15,
      },
      {
        valid: 'отрасль',
        invalid: 'отросль',
        differenceIndexes: [4],
        id: 16,
      },
      {
        valid: 'росток',
        invalid: 'расток',
        differenceIndexes: [2],
        id: 17,
      },
      {
        valid: 'вырост',
        invalid: 'выраст',
        differenceIndexes: [4],
        id: 18,
      },
      {
        valid: 'ростовщик',
        invalid: 'растовщик',
        differenceIndexes: [2],
        id: 19,
      },
      {
        valid: 'Ростов',
        invalid: 'Растов',
        differenceIndexes: [2],
        id: 20,
      },
      {
        valid: 'Ростислав',
        invalid: 'Растислав',
        differenceIndexes: [2],
        id: 21,
      },
      {
        valid: 'равнина',
        invalid: 'ровнина',
        differenceIndexes: [2],
        id: 22,
      },
      {
        valid: 'сочетать',
        invalid: 'сочитать',
        differenceIndexes: [4],
        id: 23,
      },
      {
        valid: 'аккомпанемент',
        invalid: 'аккомпонемент',
        differenceIndexes: [8],
        id: 24,
      },
      {
        valid: 'бюллетень',
        invalid: 'беллютень',
        differenceIndexes: [2],
        id: 25,
      },
      {
        valid: 'брошюра',
        invalid: 'брошура',
        differenceIndexes: [5],
        id: 26,
      },
      {
        valid: 'вестибюль',
        invalid: 'вестебюль',
        differenceIndexes: [5],
        id: 27,
      },
      {
        valid: 'винегрет',
        invalid: 'винигрет',
        differenceIndexes: [4],
        id: 28,
      },
      {
        valid: 'экстремальный',
        invalid: 'экстримальный',
        differenceIndexes: [5],
        id: 29,
      },
      {
        valid: 'укротить',
        invalid: 'укратить',
        differenceIndexes: [4],
        id: 30,
      },
      {
        valid: 'дирижёр',
        invalid: 'дерижёр',
        differenceIndexes: [2],
        id: 31,
      },
      {
        valid: 'иждивенец',
        invalid: 'иждевенец',
        differenceIndexes: [4],
        id: 32,
      },
      {
        valid: 'катастрофа',
        invalid: 'катострофа',
        differenceIndexes: [4],
        id: 33,
      },

      {
        valid: 'лелеять',
        invalid: 'лелееть',
        differenceIndexes: [5],
        id: 34,
      },
      {
        valid: 'палисадник',
        invalid: 'палесадник',
        differenceIndexes: [4],
        id: 35,
      },
      {
        valid: 'президиум',
        invalid: 'призидиум',
        differenceIndexes: [3],
        id: 36,
      },
      {
        valid: 'преодолеть',
        invalid: 'приодолеть',
        differenceIndexes: [3],
        id: 37,
      },
      {
        valid: 'преобразовать',
        invalid: 'приобразовать',
        differenceIndexes: [3],
        id: 38,
      },
      {
        valid: 'прецедент',
        invalid: 'прицедент',
        differenceIndexes: [3],
        id: 39,
      },
      {
        valid: 'привилегия',
        invalid: 'превилегия',
        differenceIndexes: [3],
        id: 40,
      },
      {
        valid: 'примитивный',
        invalid: 'премитивный',
        differenceIndexes: [3],
        id: 41,
      },
      {
        valid: 'приоритет',
        invalid: 'преоритет',
        differenceIndexes: [3],
        id: 42,
      },
      {
        valid: 'резидент',
        invalid: 'ризидент',
        differenceIndexes: [2],
        id: 43,
      },
      {
        valid: 'спартакиада',
        invalid: 'спортакиада',
        differenceIndexes: [3],
        id: 44,
      },
      {
        valid: 'стипендия',
        invalid: 'степендия',
        differenceIndexes: [3],
        id: 45,
      },
      {
        valid: 'трясина',
        invalid: 'тресина',
        differenceIndexes: [3],
        id: 46,
      },
      {
        valid: 'университет',
        invalid: 'уневерситет',
        differenceIndexes: [3],
        id: 47,
      },
      {
        valid: 'веять',
        invalid: 'вееть',
        differenceIndexes: [3],
        id: 48,
      },
      {
        valid: 'блеять',
        invalid: 'блеить',
        differenceIndexes: [4],
        id: 49,
      },
      {
        valid: 'лаять',
        invalid: 'лаить',
        differenceIndexes: [3],
        id: 50,
      },
      {
        valid: 'кашлять',
        invalid: 'кашлить',
        differenceIndexes: [5],
        id: 51,
      },
      {
        valid: 'каяться',
        invalid: 'каиться',
        differenceIndexes: [3],
        id: 52,
      },
      {
        valid: 'клеить',
        invalid: 'клееть',
        differenceIndexes: [4],
        id: 53,
      },
      {
        valid: 'вялить',
        invalid: 'вялеть',
        differenceIndexes: [4],
        id: 54,
      },
      {
        valid: 'строить',
        invalid: 'строеть',
        differenceIndexes: [5],
        id: 55,
      },
      {
        valid: 'жалить',
        invalid: 'жалеть',
        differenceIndexes: [4],
        id: 56,
      },
      {
        valid: 'метить',
        invalid: 'мететь',
        differenceIndexes: [4],
        id: 57,
      },
      {
        valid: 'молвить',
        invalid: 'молветь',
        differenceIndexes: [5],
        id: 58,
      },
      {
        valid: 'беспокоиться',
        invalid: 'беспокоеться',
        differenceIndexes: [8],
        id: 59,
      },
      {
        valid: 'осилить',
        invalid: 'осилеть',
        differenceIndexes: [5],
        id: 60,
      },
      {
        valid: 'ездить',
        invalid: 'ездеть',
        differenceIndexes: [5],
        id: 61,
      },
      {
        valid: 'бросить',
        invalid: 'бросеть',
        differenceIndexes: [5],
        id: 62,
      },
      {
        valid: 'мучить',
        invalid: 'мучать',
        differenceIndexes: [5],
        id: 63,
      },
      {
        valid: 'приемлемый',
        invalid: 'приемлимый',
        differenceIndexes: [7],
        id: 64,
      },
      {
        valid: 'незыблемый',
        invalid: 'незыблимый',
        differenceIndexes: [7],
        id: 65,
      },
      {
        valid: 'неотъемлемый',
        invalid: 'неотъемлимый',
        differenceIndexes: [9],
        id: 66,
      },
      {
        valid: 'движимый',
        invalid: 'движемый',
        differenceIndexes: [5],
        id: 67,
      },
      {
        valid: 'юродивый',
        invalid: 'юродевый',
        differenceIndexes: [5],
        id: 68,
      },
      {
        valid: 'баиньки',
        invalid: 'баеньки',
        differenceIndexes: [3],
        id: 69,
      },
      {
        valid: 'заинька',
        invalid: 'заенька',
        differenceIndexes: [3],
        id: 70,
      },
      {
        valid: 'паинька',
        invalid: 'паенька',
        differenceIndexes: [3],
        id: 71,
      },
      {
        valid: 'претерпеть',
        invalid: 'притерпеть',
        differenceIndexes: [3],
        id: 72,
      },
      {
        valid: 'притерпеться',
        invalid: 'претерпеться',
        differenceIndexes: [3],
        id: 73,
      },
      {
        valid: 'привратник',
        invalid: 'превратник',
        differenceIndexes: [3],
        id: 74,
      },
      {
        valid: 'прообраз',
        invalid: 'праобраз',
        differenceIndexes: [3],
        id: 75,
      },
      {
        valid: 'панъевропейский',
        invalid: 'паньевропейский',
        differenceIndexes: [4],
        id: 76,
      },
      {
        valid: 'продлевать',
        invalid: 'продливать',
        differenceIndexes: [6],
        id: 77,
      },
      {
        valid: 'затмевать',
        invalid: 'затмивать',
        differenceIndexes: [5],
        id: 78,
      },
      {
        valid: 'застревать',
        invalid: 'застривать',
        differenceIndexes: [6],
        id: 79,
      },
      {
        valid: 'обуревать',
        invalid: 'обуривать',
        differenceIndexes: [5],
        id: 80,
      },
      {
        valid: 'встревать',
        invalid: 'встривать',
        differenceIndexes: [5],
        id: 81,
      },
      {
        valid: 'комендант',
        invalid: 'камендант',
        differenceIndexes: [2],
        id: 82,
      },
      {
        valid: 'интеллигентный',
        invalid: 'интиллигентный',
        differenceIndexes: [4],
        id: 83,
      },
      {
        valid: 'директор',
        invalid: 'деректор',
        differenceIndexes: [2],
        id: 84,
      },
      {
        valid: 'стратегия',
        invalid: 'стротегия',
        differenceIndexes: [4],
        id: 85,
      },
      {
        valid: 'велосипед',
        invalid: 'велосепед',
        differenceIndexes: [6],
        id: 86,
      },
      {
        valid: 'менталитет',
        invalid: 'менталетет',
        differenceIndexes: [7],
        id: 87,
      },
      {
        valid: 'президент',
        invalid: 'призидент',
        differenceIndexes: [3],
        id: 88,
      },
      {
        valid: 'абитуриент',
        invalid: 'абетуриент',
        differenceIndexes: [3],
        id: 89,
      },
      {
        valid: 'циклон',
        invalid: 'цеклон',
        differenceIndexes: [2],
        id: 90,
      },
      {
        valid: 'акварельный',
        invalid: 'акворельный',
        differenceIndexes: [4],
        id: 91,
      },
      {
        valid: 'карикатура',
        invalid: 'корикатура',
        differenceIndexes: [2],
        id: 92,
      },
      {
        valid: 'комфорт',
        invalid: 'камфорт',
        differenceIndexes: [2],
        id: 93,
      },
      {
        valid: 'цикорий',
        invalid: 'цекорий',
        differenceIndexes: [2],
        id: 94,
      },
      {
        valid: 'инициалы',
        invalid: 'инециалы',
        differenceIndexes: [3],
        id: 95,
      },
      {
        valid: 'габариты',
        invalid: 'габориты',
        differenceIndexes: [4],
        id: 96,
      },
      {
        valid: 'эксперимент',
        invalid: 'эксперемент',
        differenceIndexes: [7],
        id: 97,
      },
      {
        valid: 'кастрюля',
        invalid: 'кострюля',
        differenceIndexes: [2],
        id: 98,
      },
      {
        valid: 'портрет',
        invalid: 'партрет',
        differenceIndexes: [2],
        id: 99,
      },
    ],
  },

  'Морфологические нормы': {
    type: 'primary',
    inHeader: true,

    items: [
      {
        valid: 'инструкторы',
        invalid: 'инструктора',
        id: 0,
      },
      {
        valid: 'редакторы',
        invalid: 'редактора',
        id: 1,
      },
      {
        valid: 'лекторы',
        invalid: 'лектора',
        id: 2,
      },
      {
        valid: 'конструкторы',
        invalid: 'конструктора',
        id: 3,
      },
      {
        valid: 'прожекторы',
        invalid: 'прожектора',
        id: 4,
      },
      {
        valid: 'секторы',
        invalid: 'сектора',
        id: 5,
      },
      {
        valid: 'инженеры',
        invalid: 'инженера',
        id: 6,
      },
      {
        valid: 'шофёры',
        invalid: 'шофера',
        id: 7,
      },
      {
        valid: 'бухгалтеры',
        invalid: 'бухгалтера',
        id: 8,
      },
      {
        valid: 'диспетчеры',
        invalid: 'диспетчера',
        id: 9,
      },
      {
        valid: 'договоры',
        invalid: 'договора',
        id: 10,
      },
      {
        valid: 'драйверы',
        invalid: 'драйвера',
        id: 11,
      },
      {
        valid: 'слесари',
        invalid: 'слесаря',
        id: 12,
      },
      {
        valid: 'токари',
        invalid: 'токаря',
        id: 13,
      },
      {
        valid: 'возрасты',
        invalid: 'возраста',
        id: 14,
      },
      {
        valid: 'кремы',
        invalid: 'крема',
        id: 15,
      },
      {
        valid: 'директора',
        invalid: 'директоры',
        id: 16,
      },
      {
        valid: 'профессора',
        invalid: 'профессоры',
        id: 17,
      },
      {
        valid: 'инспектора',
        invalid: 'инспекторы',
        id: 18,
      },
      {
        valid: 'доктора',
        invalid: 'докторы',
        id: 19,
      },
      {
        valid: 'катера',
        invalid: 'катеры',
        id: 20,
      },
      {
        valid: 'ордера',
        invalid: 'ордеры',
        id: 21,
      },
      {
        valid: 'тенора',
        invalid: 'теноры',
        id: 22,
      },
      {
        valid: 'фельдшера',
        invalid: 'фельдшеры',
        id: 23,
      },
      {
        valid: 'флюгера',
        invalid: 'флюгеры',
        id: 24,
      },
      {
        valid: 'хутора',
        invalid: 'хуторы',
        id: 25,
      },
      {
        valid: 'шулера',
        invalid: 'шулеры',
        id: 26,
      },
      {
        valid: 'буфера',
        invalid: 'буферы',
        id: 27,
      },
      {
        valid: 'веера',
        invalid: 'вееры',
        id: 28,
      },
      {
        valid: 'повара',
        invalid: 'повары',
        id: 29,
      },
      {
        valid: 'отпуска',
        invalid: 'отпуски',
        id: 30,
      },
      {
        valid: 'паруса',
        invalid: 'парусы',
        id: 31,
      },
      {
        valid: 'паспорта',
        invalid: 'паспорты',
        id: 32,
      },
      {
        valid: 'погреба',
        invalid: 'погребы',
        id: 33,
      },
      {
        valid: 'р.п.апельсинов',
        invalid: 'р.п.апельсин',
        id: 34,
      },
      {
        valid: 'борта',
        invalid: 'борты',
        id: 35,
      },
      {
        valid: 'черепа',
        invalid: 'черепы',
        id: 36,
      },
      {
        valid: 'р.п.бананов',
        invalid: 'р.п.банан',
        id: 37,
      },
      {
        valid: 'р.п.томатов',
        invalid: 'р.п.томат',
        id: 38,
      },
      {
        valid: 'р.п.помидоров',
        invalid: 'р.п.помидор',
        id: 39,
      },
      {
        valid: 'р.п.абрикосов',
        invalid: 'р.п.абрикос',
        id: 40,
      },
      {
        valid: 'р.п.мандаринов',
        invalid: 'р.п.мандарин',
        id: 41,
      },
      {
        valid: 'р.п.яблок',
        invalid: 'р.п.яблоков',
        id: 42,
      },
      {
        valid: 'р.п.груш',
        invalid: 'р.п.грушей',
        id: 43,
      },
      {
        valid: 'р.п.дынь',
        invalid: 'р.п.дыней',
        id: 44,
      },
      {
        valid: 'р.п.казахов',
        invalid: 'р.п.казах',
        id: 45,
      },
      {
        valid: 'р.п.калмыков',
        invalid: 'р.п.калмык',
        id: 46,
      },
      {
        valid: 'р.п.киргизов',
        invalid: 'р.п.киргиз',
        id: 47,
      },
      {
        valid: 'р.п.монголов',
        invalid: 'р.п.монгол',
        id: 48,
      },
      {
        valid: 'р.п.армян',
        invalid: 'р.п.армянинов',
        id: 49,
      },
      {
        valid: 'р.п.башкир',
        invalid: 'р.п.башкиров',
        id: 50,
      },
      {
        valid: 'р.п.болгар',
        invalid: 'р.п.болгаров',
        id: 51,
      },
      {
        valid: 'грузин',
        invalid: 'грузинов',
        id: 52,
      },
      {
        valid: 'татар',
        invalid: 'татаров',
        id: 53,
      },
      {
        valid: 'р.п.цыган',
        invalid: 'р.п.цыганов',
        id: 54,
      },
      {
        valid: 'р.п.турок',
        invalid: 'р.п.турков',
        id: 55,
      },
      {
        valid: 'р.п.бурят',
        invalid: 'р.п.бурятов',
        id: 56,
      },
      {
        valid: 'р.п.байтов',
        invalid: 'р.п.байт',
        id: 57,
      },
      {
        valid: 'р.п.гектаров',
        invalid: 'р.п.гектар',
        id: 58,
      },
      {
        valid: 'р.п.грамов',
        invalid: 'р.п.грамм',
        id: 59,
      },
      {
        valid: 'р.п.килограммов',
        invalid: 'р.п.килограмм',
        id: 60,
      },
      {
        valid: 'р.п.ампер',
        invalid: 'р.п.амперов',
        id: 61,
      },
      {
        valid: 'р.п.аршин',
        invalid: 'р.п.аршинов',
        id: 62,
      },
      {
        valid: 'р.п.носков',
        invalid: 'р.п.носок',
        id: 63,
      },
      {
        valid: 'р.п.гольфов',
        invalid: 'р.п.гольф',
        id: 64,
      },
      {
        valid: 'р.п.рельсов',
        invalid: 'р.п.рельс',
        id: 65,
      },
      {
        valid: 'джинсов',
        invalid: 'джинс',
        id: 66,
      },
      {
        valid: 'р.п.бриджей',
        invalid: 'р.п.бридж',
        id: 67,
      },
      {
        valid: 'р.п.ботинок',
        invalid: 'р.п.ботинков',
        id: 68,
      },
      {
        valid: 'р.п.чулок',
        invalid: 'р.п.чулков',
        id: 69,
      },
      {
        valid: 'р.п.шорт',
        invalid: 'р.п.шортов',
        id: 70,
      },
      {
        valid: 'р.п.туфель',
        invalid: 'р.п.туфлей',
        id: 71,
      },
      {
        valid: 'р.п.сапог',
        invalid: 'р.п.сапогов',
        id: 72,
      },
      {
        valid: 'р.п.тапок',
        invalid: 'р.п.тапков',
        id: 73,
      },
      {
        valid: 'тапок',
        invalid: 'тапка',
        id: 74,
      },
      {
        valid: 'р.п.галош',
        invalid: 'р.п.галошей',
        id: 75,
      },
      {
        valid: 'р.п.валенок',
        invalid: 'р.п.валенков',
        id: 76,
      },
      {
        valid: 'р.п.серёг',
        invalid: 'р.п.серёжек',
        id: 77,
      },
      {
        valid: 'р.п.солдат',
        invalid: 'р.п.солдатов',
        id: 78,
      },
      {
        valid: 'р.п.гусар',
        invalid: 'р.п.гусаров',
        id: 79,
      },
      {
        valid: 'р.п.кадет',
        invalid: 'р.п.кадетов',
        id: 80,
      },
      {
        valid: 'р.п.партизан',
        invalid: 'р.п.партизанов',
        id: 81,
      },
      {
        valid: 'р.п.яблонь',
        invalid: 'р.п.яблоней',
        id: 82,
      },
      {
        valid: 'р.п.нянь',
        invalid: 'р.п.няней',
        id: 83,
      },
      {
        valid: 'р.п.барышень',
        invalid: 'р.п.барышней',
        id: 84,
      },
      {
        valid: 'р.п.кухонь',
        invalid: 'р.п.кухней',
        id: 85,
      },
      {
        valid: 'р.п.басен',
        invalid: 'р.п.басней',
        id: 86,
      },
      {
        valid: 'р.п.башен',
        invalid: 'р.п.башней',
        id: 87,
      },
      {
        valid: 'р.п.вишен',
        invalid: 'р.п.вишней',
        id: 88,
      },
      {
        valid: 'р.п.пашен',
        invalid: 'р.п.пашней',
        id: 89,
      },
      {
        valid: 'р.п.спален',
        invalid: 'р.п.спальней',
        id: 90,
      },
      {
        valid: 'р.п.мускулов',
        invalid: 'р.п.мускул',
        id: 91,
      },
      {
        valid: 'р.п.чипсов',
        invalid: 'р.п.чипс',
        id: 92,
      },
      {
        valid: 'р.п.макарон',
        invalid: 'р.п.макаронов',
        id: 93,
      },
    ],
  },

  'н/нн': {
    type: 'primary',
    inHeader: true,

    items: [
      {
        valid: 'бараний',
        invalid: 'баранний',
        id: 0,
      },
      {
        valid: 'багряный',
        invalid: 'багрянный',
        id: 1,
      },
      {
        valid: 'безветренный',
        invalid: 'безветреный',
        id: 2,
      },
      {
        valid: 'бесприданница',
        invalid: 'бесприданица',
        id: 3,
      },
      {
        valid: 'бессребреник',
        invalid: 'бессребренник',
        id: 4,
      },
      {
        valid: 'блаженный',
        invalid: 'блаженый',
        id: 5,
      },
      {
        valid: 'вареник',
        invalid: 'варенник',
        id: 6,
      },
      {
        valid: 'венчанный',
        invalid: 'венчаный',
        id: 7,
      },
      {
        valid: 'ветреный',
        invalid: 'ветренный',
        id: 8,
      },
      {
        valid: 'виденный',
        invalid: 'виденый',
        id: 9,
      },
      {
        valid: 'вороной',
        invalid: 'воронной',
        id: 10,
      },
      {
        valid: 'гостиная',
        invalid: 'гостинная',
        id: 11,
      },
      {
        valid: 'деревянный',
        invalid: 'деревяный',
        id: 12,
      },
      {
        valid: 'жданный',
        invalid: 'жданый',
        id: 13,
      },
      {
        valid: 'жёваный',
        invalid: 'жёванный',
        id: 14,
      },
      {
        valid: 'желанный',
        invalid: 'желаный',
        id: 15,
      },
      {
        valid: 'жеманный',
        invalid: 'жеманый',
        id: 16,
      },
      {
        valid: 'завещанный',
        invalid: 'завещаный',
        id: 17,
      },
      {
        valid: 'измождённый',
        invalid: 'измождёный',
        id: 18,
      },
      {
        valid: 'изысканный',
        invalid: 'изысканый',
        id: 19,
      },
      {
        valid: 'клёваный',
        invalid: 'клёванный',
        id: 20,
      },
      {
        valid: 'кованый',
        invalid: 'кованный',
        id: 21,
      },
      {
        valid: 'крещёный',
        invalid: 'крещённый',
        id: 22,
      },
      {
        valid: 'мудрёный',
        invalid: 'мудрённый',
        id: 23,
      },
      {
        valid: 'мученик',
        invalid: 'мученник',
        id: 24,
      },
      {
        valid: 'холстинный',
        invalid: 'холстиный',
        id: 25,
      },
      {
        valid: 'диковинный',
        invalid: 'диковиный',
        id: 26,
      },
      {
        valid: 'старинный',
        invalid: 'стариный',
        id: 27,
      },
      {
        valid: 'названый брат',
        invalid: 'названный брат',
        id: 28,
      },
      {
        valid: 'неведанный',
        invalid: 'неведаный',
        id: 29,
      },
      {
        valid: 'негаданный',
        invalid: 'негаданый',
        id: 30,
      },
      {
        valid: 'нежданный',
        invalid: 'нежданый',
        id: 31,
      },
      {
        valid: 'нежеланный',
        invalid: 'нежеланый',
        id: 32,
      },
      {
        valid: 'неожиданный',
        invalid: 'неожиданый',
        id: 33,
      },
      {
        valid: 'неслыханный',
        invalid: 'неслыханый',
        id: 34,
      },
      {
        valid: 'нечаянный',
        invalid: 'нечаяный',
        id: 35,
      },
      {
        valid: 'обезьяний',
        invalid: 'обезьянний',
        id: 36,
      },
      {
        valid: 'обещанный',
        invalid: 'обещаный',
        id: 37,
      },
      {
        valid: 'окаянный',
        invalid: 'окаяный',
        id: 38,
      },
      {
        valid: 'оловянный',
        invalid: 'оловяный',
        id: 39,
      },
      {
        valid: 'посажёный отец',
        invalid: 'посажённый отец',
        id: 40,
      },
      {
        valid: 'подлинный',
        invalid: 'подлиный',
        id: 41,
      },
      {
        valid: 'преданный',
        invalid: 'преданый',
        id: 42,
      },
      {
        valid: 'приданое',
        invalid: 'приданное',
        id: 43,
      },
      {
        valid: 'прощёное воскресенье',
        invalid: 'прощённое воскресенье',
        id: 44,
      },
      {
        valid: 'пряный',
        invalid: 'прянный',
        id: 45,
      },
      {
        valid: 'пудреница',
        invalid: 'пудренница',
        id: 46,
      },
      {
        valid: 'раненный в бою',
        invalid: 'раненый в бою',
        id: 47,
      },
      {
        valid: 'раненый',
        invalid: 'раненный',
        id: 48,
      },
      {
        valid: 'роженица',
        invalid: 'роженница',
        id: 49,
      },
      {
        valid: 'румяный',
        invalid: 'румянный',
        id: 50,
      },
      {
        valid: 'самонадеянный',
        invalid: 'самонадеяный',
        id: 51,
      },
      {
        valid: 'свиной',
        invalid: 'свинной',
        id: 52,
      },
      {
        valid: 'серебреник',
        invalid: 'серебренник',
        id: 53,
      },
      {
        valid: 'слышанный',
        invalid: 'слышаный',
        id: 54,
      },
      {
        valid: 'смышлёный',
        invalid: 'смышлённый',
        id: 55,
      },
      {
        valid: 'ставленник',
        invalid: 'ставленик',
        id: 56,
      },
      {
        valid: 'стеклянный',
        invalid: 'стекляный',
        id: 57,
      },
      {
        valid: 'суженый',
        invalid: 'суженный',
        id: 58,
      },
      {
        valid: 'труженик',
        invalid: 'труженник',
        id: 59,
      },
    ],
  },

  'пре-при': {
    type: 'primary',
    inHeader: true,

    items: [
      {
        id: 0,
        valid: 'без прикрас',
        invalid: 'без прекрас',
        differenceIndexes: [3],
      },
      {
        id: 1,
        valid: 'беспристрастный',
        invalid: 'беспрестрастный',
        differenceIndexes: [5],
      },
      {
        id: 2,
        valid: 'придаточный',
        invalid: 'предаточный',
        differenceIndexes: [3],
      },
      {
        id: 3,
        valid: 'приобрёл',
        invalid: 'преобрёл',
        differenceIndexes: [3],
      },
      {
        id: 4,
        valid: 'приобщиться',
        invalid: 'преобщиться',
        differenceIndexes: [3],
      },
      {
        id: 5,
        valid: 'приобретение',
        invalid: 'преобретение',
        differenceIndexes: [3],
      },
      {
        id: 6,
        valid: 'придавать (значение)',
        invalid: 'предавать (значение)',
        differenceIndexes: [3],
      },
      {
        id: 7,
        valid: 'предавать (друга)',
        invalid: 'придавать (друга)',
        differenceIndexes: [3],
      },
      {
        id: 8,
        valid: 'приравнять',
        invalid: 'преравнять',
        differenceIndexes: [3],
      },
      {
        id: 9,
        valid: 'пристегнуть',
        invalid: 'престегнуть',
        differenceIndexes: [3],
      },
      {
        id: 10,
        valid: 'непримиримый',
        invalid: 'непремиримый',
        differenceIndexes: [3],
      },
      {
        id: 11,
        valid: 'призвание',
        invalid: 'презвание',
        differenceIndexes: [3],
      },
      {
        id: 12,
        valid: 'приноровиться',
        invalid: 'преноровиться',
        differenceIndexes: [3],
      },
      {
        id: 13,
        valid: 'принаряженный',
        invalid: 'пренаряженный',
        differenceIndexes: [3],
      },
      {
        id: 14,
        valid: 'пристроенный',
        invalid: 'престроенный',
        differenceIndexes: [3],
      },
      {
        id: 15,
        valid: 'пригорок',
        invalid: 'прегорок',
        differenceIndexes: [3],
      },
      {
        id: 16,
        valid: 'прикарманить',
        invalid: 'прекарманить',
        differenceIndexes: [3],
      },
      {
        id: 17,
        valid: 'прислушаться',
        invalid: 'преслушаться',
        differenceIndexes: [3],
      },
      {
        id: 18,
        valid: 'привратник',
        invalid: 'превратник',
        differenceIndexes: [3],
      },
      {
        id: 19,
        valid: 'преодолевать',
        invalid: 'приодолевать',
        differenceIndexes: [3],
      },
      {
        id: 20,
        valid: 'преобразование',
        invalid: 'приобразование',
        differenceIndexes: [3],
      },
      {
        id: 21,
        valid: 'президент',
        invalid: 'призидент',
        differenceIndexes: [3],
      },
      {
        id: 22,
        valid: 'прекрасный',
        invalid: 'прикрасный',
        differenceIndexes: [3],
      },
      {
        id: 23,
        valid: 'превозмочь',
        invalid: 'привозмочь',
        differenceIndexes: [3],
      },
      {
        id: 24,
        valid: 'превратить',
        invalid: 'привратить',
        differenceIndexes: [3],
      },
      {
        id: 25,
        valid: 'преграда',
        invalid: 'приграда',
        differenceIndexes: [3],
      },
      {
        id: 26,
        valid: 'превратности',
        invalid: 'привратности',
        differenceIndexes: [3],
      },
      {
        id: 27,
        valid: 'пререкаться',
        invalid: 'прирекаться',
        differenceIndexes: [3],
      },
      {
        id: 28,
        valid: 'преуспеть',
        invalid: 'приуспеть',
        differenceIndexes: [3],
      },
      {
        id: 29,
        valid: 'пресмыкаться',
        invalid: 'присмыкаться',
        differenceIndexes: [3],
      },
      {
        id: 30,
        valid: 'преследовать',
        invalid: 'приследовать',
        differenceIndexes: [3],
      },
      {
        id: 31,
        valid: 'преломление',
        invalid: 'приломление',
        differenceIndexes: [3],
      },
      {
        id: 32,
        valid: 'прекратить',
        invalid: 'прикратить',
        differenceIndexes: [3],
      },
      {
        id: 33,
        valid: 'преувеличивать',
        invalid: 'приувеличивать',
        differenceIndexes: [3],
      },
      {
        id: 34,
        valid: 'преодолеть',
        invalid: 'приодолеть',
        differenceIndexes: [3],
      },
      {
        id: 35,
        valid: 'превысить',
        invalid: 'привысить',
        differenceIndexes: [3],
      },
      {
        id: 36,
        valid: 'предание',
        invalid: 'придание',
        differenceIndexes: [3],
      },
      {
        id: 37,
        valid: 'преемственность',
        invalid: 'приемственность',
        differenceIndexes: [3],
      },
      {
        id: 38,
        valid: 'преобладать',
        invalid: 'приобладать',
        differenceIndexes: [3],
      },
      {
        id: 39,
        valid: 'преступник',
        invalid: 'приступник',
        differenceIndexes: [3],
      },
      {
        id: 40,
        valid: 'престижный',
        invalid: 'пристижный',
        differenceIndexes: [3],
      },
      {
        id: 41,
        valid: 'премудрый',
        invalid: 'примудрый',
        differenceIndexes: [3],
      },
      {
        id: 42,
        valid: 'превратный',
        invalid: 'привратный',
        differenceIndexes: [3],
      },
      {
        id: 43,
        valid: 'прекращение',
        invalid: 'прикращение',
        differenceIndexes: [3],
      },
      {
        id: 44,
        valid: 'преподаватель',
        invalid: 'приподаватель',
        differenceIndexes: [3],
      },
      {
        id: 45,
        valid: 'приглушить',
        invalid: 'преглушить',
        differenceIndexes: [3],
      },
      {
        id: 46,
        valid: 'приблизиться',
        invalid: 'преблизиться',
        differenceIndexes: [3],
      },
      {
        id: 47,
        valid: 'присоединить',
        invalid: 'пресоединить',
        differenceIndexes: [3],
      },
      {
        id: 48,
        valid: 'пребывать (дома)',
        invalid: 'прибывать (дома)',
        differenceIndexes: [3],
      },
      {
        id: 49,
        valid: 'прибывает (в столицу)',
        invalid: 'пребывает (в столицу)',
        differenceIndexes: [3],
      },
      {
        id: 50,
        valid: 'признать',
        invalid: 'презнать',
        differenceIndexes: [3],
      },
      {
        id: 51,
        valid: 'приготовить',
        invalid: 'преготовить',
        differenceIndexes: [3],
      },
      {
        id: 52,
        valid: 'приспособить',
        invalid: 'преспособить',
        differenceIndexes: [3],
      },
      {
        id: 53,
        valid: 'приближение',
        invalid: 'преближение',
        differenceIndexes: [3],
      },
      {
        id: 54,
        valid: 'привыкнуть',
        invalid: 'превыкнуть',
        differenceIndexes: [3],
      },
      {
        id: 55,
        valid: 'присмотреться',
        invalid: 'пресмотреться',
        differenceIndexes: [3],
      },
      {
        id: 56,
        valid: 'присоединение',
        invalid: 'пресоединение',
        differenceIndexes: [3],
      },
      {
        id: 57,
        valid: 'приблизительный',
        invalid: 'преблизительный',
        differenceIndexes: [3],
      },
      {
        id: 58,
        valid: 'пристанище',
        invalid: 'престанище',
        differenceIndexes: [3],
      },
      {
        id: 59,
        valid: 'причудливый',
        invalid: 'пречудливый',
        differenceIndexes: [3],
      },
      {
        id: 60,
        valid: 'привидение',
        invalid: 'превидение',
        differenceIndexes: [3],
      },
      {
        id: 61,
        valid: 'приблизительно',
        invalid: 'преблизительно',
        differenceIndexes: [3],
      },
    ],
  },

  'Виды союзов': {
    type: 'unions',
    inHeader: true,

    items: [
      {
        word: 'И',
        unionType: 'Сочинительный',
        id: 0,
      },
      {
        word: 'ДА',
        unionType: 'Сочинительный',
        id: 1,
      },
      {
        word: 'НИ…НИ',
        unionType: 'Сочинительный',
        id: 2,
      },
      {
        word: 'ТОЖЕ',
        unionType: 'Сочинительный',
        id: 3,
      },
      {
        word: 'ТАКЖЕ',
        unionType: 'Сочинительный',
        id: 4,
      },
      {
        word: 'А',
        unionType: 'Сочинительный',
        id: 5,
      },
      {
        word: 'НО',
        unionType: 'Сочинительный',
        id: 6,
      },
      {
        word: 'ЗАТО',
        unionType: 'Сочинительный',
        id: 7,
      },
      {
        word: 'ОДНАКО',
        unionType: 'Сочинительный',
        id: 8,
      },
      {
        word: 'ИЛИ',
        unionType: 'Сочинительный',
        id: 9,
      },
      {
        word: 'ЛИБО',
        unionType: 'Сочинительный',
        id: 10,
      },
      {
        word: 'ТО…ТО',
        unionType: 'Сочинительный',
        id: 11,
      },
      {
        word: 'НЕ ТО…НЕ ТО',
        unionType: 'Сочинительный',
        id: 12,
      },
      {
        word: 'КАК',
        unionType: 'Подчинительный',
        id: 13,
      },
      {
        word: 'ЧТОБЫ',
        unionType: 'Подчинительный',
        id: 14,
      },
      {
        word: 'БУДТО',
        unionType: 'Подчинительный',
        id: 15,
      },
      {
        word: 'КОГДА',
        unionType: 'Подчинительный',
        id: 16,
      },
      {
        word: 'КАК ТОЛЬКО',
        unionType: 'Подчинительный',
        id: 17,
      },
      {
        word: 'МЕЖДУ ТЕМ',
        unionType: 'Подчинительный',
        id: 18,
      },
      {
        word: 'ЛИШЬ',
        unionType: 'Подчинительный',
        id: 19,
      },
      {
        word: 'ЕДВА',
        unionType: 'Подчинительный',
        id: 20,
      },
      {
        word: 'ПОКА',
        unionType: 'Подчинительный',
        id: 21,
      },
      {
        word: 'ИБО',
        unionType: 'Подчинительный',
        id: 22,
      },
      {
        word: 'ПОТОМУ',
        unionType: 'Подчинительный',
        id: 23,
      },
      {
        word: 'ТАК КАК',
        unionType: 'Подчинительный',
        id: 24,
      },
      {
        word: 'ЧТОБЫ',
        unionType: 'Подчинительный',
        id: 25,
      },
      {
        word: 'ЕСЛИ',
        unionType: 'Подчинительный',
        id: 26,
      },
      {
        word: 'ХОТЯ',
        unionType: 'Подчинительный',
        id: 27,
      },
      {
        word: 'ПУСТЬ',
        unionType: 'Подчинительный',
        id: 28,
      },
      {
        word: 'НЕСМОТРЯ НА ТО ЧТО',
        unionType: 'Подчинительный',
        id: 29,
      },
      {
        word: 'БУДТО',
        unionType: 'Подчинительный',
        id: 30,
      },
      {
        word: 'СЛОВНО',
        unionType: 'Подчинительный',
        id: 31,
      },
      {
        word: 'КОТОРЫЙ',
        unionType: 'Подчинительный',
        id: 32,
      },
      {
        word: 'ЛИ',
        unionType: 'Подчинительный',
        id: 33,
      },
      {
        word: 'КАКОЙ',
        unionType: 'Подчинительный',
        id: 34,
      },
      {
        word: 'ЧЕЙ',
        unionType: 'Подчинительный',
        id: 35,
      },
      {
        word: 'ГДЕ',
        unionType: 'Подчинительный',
        id: 36,
      },
      {
        word: 'КУДА',
        unionType: 'Подчинительный',
        id: 37,
      },
      {
        word: 'ОТКУДА',
        unionType: 'Подчинительный',
        id: 38,
      },
      {
        word: 'ПОЧЕМУ',
        unionType: 'Подчинительный',
        id: 39,
      },
      {
        word: 'ЗАЧЕМ',
        unionType: 'Подчинительный',
        id: 40,
      },
      {
        word: 'КТО',
        unionType: 'Подчинительный',
        id: 41,
      },
      {
        word: 'НАСКОЛЬКО',
        unionType: 'Подчинительный',
        id: 42,
      },
      {
        word: 'КАКОВ',
        unionType: 'Подчинительный',
        id: 43,
      },
    ],
  },

  'Наречия (6 класс)': {
    type: 'primary',
    inHeader: false,
    items: [
      {
        valid: 'без ведома',
        invalid: 'безведома',
        id: 0,
      },
      {
        valid: 'без оглядки',
        invalid: 'безоглядки',
        id: 1,
      },
      {
        valid: 'без отказа',
        invalid: 'безотказа',
        id: 2,
      },
      {
        valid: 'без просвета',
        invalid: 'безпросвета',
        id: 3,
      },
      {
        valid: 'без просыпу',
        invalid: 'безпросыпу',
        id: 4,
      },
      {
        valid: 'без разбору',
        invalid: 'безразбору',
        id: 5,
      },
      {
        valid: 'без спросу',
        invalid: 'безспросу',
        id: 6,
      },
      {
        valid: 'без толку',
        invalid: 'безтолку',
        id: 7,
      },
      {
        valid: 'без удержу',
        invalid: 'безудержу',
        id: 8,
      },
      {
        valid: 'без умолку',
        invalid: 'безумолку',
        id: 9,
      },
      {
        valid: 'без устали',
        invalid: 'безустали',
        id: 10,
      },
      {
        valid: 'без утайки',
        invalid: 'безутайки',
        id: 11,
      },
      {
        valid: 'бок о бок',
        invalid: 'бок-о-бок',
        id: 12,
      },
      {
        valid: 'вблизи',
        invalid: 'в близи',
        id: 13,
      },
      {
        valid: 'вбок',
        invalid: 'в бок',
        id: 14,
      },
      {
        valid: 'вброд',
        invalid: 'в брод',
        id: 15,
      },
      {
        valid: 'ввек',
        invalid: 'в век',
        id: 16,
      },
      {
        valid: 'вверх',
        invalid: 'в верх',
        id: 17,
      },
      {
        valid: 'вволю',
        invalid: 'в волю',
        id: 18,
      },
      {
        valid: 'ввысь',
        invalid: 'в высь',
        id: 19,
      },
      {
        valid: 'вглубь',
        invalid: 'в глубь',
        id: 20,
      },
      {
        valid: 'вдалеке',
        invalid: 'в далеке',
        id: 21,
      },
      {
        valid: 'вдали',
        invalid: 'в дали',
        id: 22,
      },
      {
        valid: 'вдаль',
        invalid: 'в даль',
        id: 23,
      },
      {
        valid: 'вдвойне',
        invalid: 'в двойне',
        id: 24,
      },
      {
        valid: 'вдесятеро',
        invalid: 'в десятеро',
        id: 25,
      },
      {
        valid: 'вдобавок',
        invalid: 'в добавок',
        id: 26,
      },
      {
        valid: 'вдогонку',
        invalid: 'в догонку',
        id: 27,
      },
      {
        valid: 'вдребезги',
        invalid: 'в дребезги',
        id: 28,
      },
      {
        valid: 'в заключение',
        invalid: 'взаключение',
        id: 29,
      },
      {
        valid: 'взаймы',
        invalid: 'в займы',
        id: 30,
      },
      {
        valid: 'взамен',
        invalid: 'в замен',
        id: 31,
      },
      {
        valid: 'вконец',
        invalid: 'в конец',
        id: 32,
      },
      {
        valid: 'в корне',
        invalid: 'вконце',
        id: 33,
      },
      {
        valid: 'вкось',
        invalid: 'в кось',
        id: 34,
      },
      {
        valid: 'вкривь',
        invalid: 'в кривь',
        id: 35,
      },
      {
        valid: 'вкрутую',
        invalid: 'в крутую',
        id: 36,
      },
      {
        valid: 'вкупе',
        invalid: 'в купе',
        id: 37,
      },
      {
        valid: 'влет',
        invalid: 'в лет',
        id: 38,
      },
      {
        valid: 'вмиг',
        invalid: 'в миг',
        id: 39,
      },
      {
        valid: 'в обтяжку',
        invalid: 'вобтяжку',
        id: 40,
      },
      {
        valid: 'в обхват',
        invalid: 'вобхват',
        id: 41,
      },
      {
        valid: 'в общем',
        invalid: 'вобщем',
        id: 42,
      },
      {
        valid: 'вовек',
        invalid: 'во век',
        id: 43,
      },
      {
        valid: 'вовеки',
        invalid: 'во веки',
        id: 44,
      },
      {
        valid: 'вовремя',
        invalid: 'во время',
        id: 45,
      },
      {
        valid: 'вовсе',
        invalid: 'во все',
        id: 46,
      },
      {
        valid: 'вовсю (заорать)',
        invalid: 'во всю (заорать)',
        id: 47,
      },
      {
        valid: 'во всеоружии',
        invalid: 'во все оружии',
        id: 48,
      },
      {
        valid: 'во всеуслышание',
        invalid: 'во все услышание',
        id: 49,
      },
      {
        valid: 'в одиночку',
        invalid: 'водиночку',
        id: 50,
      },
      {
        valid: 'во избежание',
        invalid: 'воизбежание',
        id: 51,
      },
      {
        valid: 'воистину',
        invalid: 'во истину',
        id: 52,
      },
      {
        valid: 'воочию',
        invalid: 'во очию',
        id: 53,
      },
      {
        valid: 'в открытую',
        invalid: 'воткрытую',
        id: 54,
      },
      {
        valid: 'впервые',
        invalid: 'в первые',
        id: 55,
      },
      {
        valid: 'вперегонки',
        invalid: 'в перегонки',
        id: 56,
      },
      {
        valid: 'вперемежку (чередовать)',
        invalid: 'в перемежку (чередовать)',
        id: 57,
      },
      {
        valid: 'вперемешку (мешать)',
        invalid: 'в перемешку (мешать)',
        id: 58,
      },
      {
        valid: 'вплотную',
        invalid: 'в плотную',
        id: 59,
      },
      {
        valid: 'вповалку',
        invalid: 'в повалку',
        id: 60,
      },
      {
        valid: 'вполоборота',
        invalid: 'в полоборота',
        id: 61,
      },
      {
        valid: 'вполовину',
        invalid: 'в половину',
        id: 62,
      },
      {
        valid: 'вполсилы',
        invalid: 'в полсилы',
        id: 63,
      },
      {
        valid: 'впопыхах',
        invalid: 'в попыхах',
        id: 64,
      },
      {
        valid: 'впору (по мерке)',
        invalid: 'в пору (по мерке)',
        id: 65,
      },
      {
        valid: 'в пору (вовремя)',
        invalid: 'впору (вовремя)',
        id: 66,
      },
      {
        valid: 'впоследствии',
        invalid: 'в последствии',
        id: 67,
      },
      {
        valid: 'впотьмах',
        invalid: 'в потьмах',
        id: 68,
      },
      {
        valid: 'вправду',
        invalid: 'в правду',
        id: 69,
      },
      {
        valid: 'вприпрыжку',
        invalid: 'в припрыжку',
        id: 70,
      },
      {
        valid: 'впустую',
        invalid: 'в пустую',
        id: 71,
      },
      {
        valid: 'вправе',
        invalid: 'в праве',
        id: 72,
      },
      {
        valid: 'вприглядку',
        invalid: 'в приглядку',
        id: 73,
      },
      {
        valid: 'вприкуску',
        invalid: 'в прикуску',
        id: 74,
      },
      {
        valid: 'вприсядку',
        invalid: 'в присядку',
        id: 75,
      },
      {
        valid: 'впритык',
        invalid: 'в притык',
        id: 76,
      },
      {
        valid: 'впроголодь',
        invalid: 'в проголодь',
        id: 77,
      },
      {
        valid: 'впрок',
        invalid: 'в прок',
        id: 78,
      },
      {
        valid: 'в рассрочку',
        invalid: 'врассрочку',
        id: 79,
      },
      {
        valid: 'врассыпную',
        invalid: 'в рассыпную',
        id: 80,
      },
      {
        valid: 'вроде',
        invalid: 'в роде',
        id: 81,
      },
      {
        valid: 'врукопашную',
        invalid: 'в рукопашную',
        id: 82,
      },
      {
        valid: 'вручную',
        invalid: 'в ручную',
        id: 83,
      },
      {
        valid: 'вряд ли',
        invalid: 'врядли',
        id: 84,
      },
      {
        valid: 'в сердцах',
        invalid: 'всердцах',
        id: 85,
      },
      {
        valid: 'всецело',
        invalid: 'все цело',
        id: 86,
      },
      {
        valid: 'в силу (вследствие)',
        invalid: 'всилу (вследствие)',
        id: 87,
      },
      {
        valid: 'в складчину',
        invalid: 'вскладчину',
        id: 88,
      },
      {
        valid: 'вскорости',
        invalid: 'в скорости',
        id: 89,
      },
      {
        valid: 'вслед',
        invalid: 'в след',
        id: 90,
      },
      {
        valid: 'вслепую',
        invalid: 'в слепую',
        id: 91,
      },
      {
        valid: 'вслух',
        invalid: 'в слух',
        id: 92,
      },
      {
        valid: 'всмятку',
        invalid: 'в смятку',
        id: 93,
      },
      {
        valid: 'в старину',
        invalid: 'встарину',
        id: 94,
      },
      {
        valid: 'встарь',
        invalid: 'в старь',
        id: 95,
      },
      {
        valid: 'всуе(напрасно)',
        invalid: 'в суе (напрасно)',
        id: 96,
      },
      {
        valid: 'втайне(сделать)',
        invalid: 'в тайне (сделать)',
        id: 97,
      },
      {
        valid: 'в тайне(хранить)',
        invalid: 'втайне (хранить)',
        id: 98,
      },
      {
        valid: 'втридорога',
        invalid: 'в тридорога',
        id: 99,
      },
      {
        valid: 'втрое',
        invalid: 'в трое',
        id: 100,
      },
      {
        valid: 'в упор',
        invalid: 'вупор',
        id: 101,
      },
      {
        valid: 'в ходу',
        invalid: 'входу',
        id: 102,
      },
      {
        valid: 'в целом',
        invalid: 'вцелом',
        id: 103,
      },
      {
        valid: 'вчистую(проиграл)',
        invalid: 'в чистую (проиграл)',
        id: 104,
      },
      {
        valid: 'вшестеро',
        invalid: 'в шестеро',
        id: 105,
      },
      {
        valid: 'вширь',
        invalid: 'в ширь',
        id: 106,
      },
      {
        valid: 'в шутку',
        invalid: 'вшутку',
        id: 107,
      },
      {
        valid: 'въявь',
        invalid: 'в явь',
        id: 108,
      },
      {
        valid: 'доверху',
        invalid: 'до верху',
        id: 109,
      },
      {
        valid: 'до крайности',
        invalid: 'докрайности',
        id: 110,
      },
      {
        valid: 'донизу',
        invalid: 'до низу',
        id: 111,
      },
      {
        valid: 'доныне',
        invalid: 'до ныне',
        id: 112,
      },
      {
        valid: 'до отказа',
        invalid: 'доотказа',
        id: 113,
      },
      {
        valid: 'до свидания',
        invalid: 'досвидания',
        id: 114,
      },
      {
        valid: 'дотла',
        invalid: 'до тла',
        id: 115,
      },
      {
        valid: 'за границей',
        invalid: 'заграницей',
        id: 116,
      },
      {
        valid: 'за границу',
        invalid: 'заграницу',
        id: 117,
      },
      {
        valid: 'замуж',
        invalid: 'за муж',
        id: 118,
      },
      {
        valid: 'внаймы',
        invalid: 'в наймы',
        id: 119,
      },
      {
        valid: 'внакидку',
        invalid: 'в накидку',
        id: 120,
      },
      {
        valid: 'внакладе',
        invalid: 'в накладе',
        id: 121,
      },
      {
        valid: 'в насмешку',
        invalid: 'внасмешку',
        id: 122,
      },
      {
        valid: 'вначале',
        invalid: 'в начале',
        id: 123,
      },
      {
        valid: 'вниз',
        invalid: 'в низ',
        id: 124,
      },
      {
        valid: 'вничью',
        invalid: 'в ничью',
        id: 125,
      },
      {
        valid: 'вновь',
        invalid: 'в новь',
        id: 126,
      },
      {
        valid: 'внутрь',
        invalid: 'в нутри',
        id: 127,
      },
      {
        valid: 'в обрез',
        invalid: 'вобрез',
        id: 128,
      },
      {
        valid: 'как раз',
        invalid: 'какраз',
        id: 129,
      },
      {
        valid: 'крест-накрест',
        invalid: 'крест накрест',
        id: 130,
      },
      {
        valid: 'на авось',
        invalid: 'наавось',
        id: 131,
      },
      {
        valid: 'на бегу',
        invalid: 'набегу',
        id: 132,
      },
      {
        valid: 'набок',
        invalid: 'на бок',
        id: 133,
      },
      {
        valid: 'навек',
        invalid: 'на век',
        id: 134,
      },
      {
        valid: 'навеки',
        invalid: 'на веки',
        id: 135,
      },
      {
        valid: 'наверх',
        invalid: 'на верх',
        id: 136,
      },
      {
        valid: 'на вид',
        invalid: 'навид',
        id: 137,
      },
      {
        valid: 'на виду',
        invalid: 'навиду',
        id: 138,
      },
      {
        valid: 'навряд ли',
        invalid: 'на вряд ли',
        id: 139,
      },
      {
        valid: 'навстречу',
        invalid: 'на встречу',
        id: 140,
      },
      {
        valid: 'навыпуск',
        invalid: 'на выпуск',
        id: 141,
      },
      {
        valid: 'навытяжку',
        invalid: 'на вытяжку',
        id: 142,
      },
      {
        valid: 'на глаз',
        invalid: 'наглаз',
        id: 143,
      },
      {
        valid: 'на глазок',
        invalid: 'наглазок',
        id: 144,
      },
      {
        valid: 'наголову',
        invalid: 'на голову',
        id: 145,
      },
      {
        valid: 'на диво',
        invalid: 'надиво',
        id: 146,
      },
      {
        valid: 'на днях',
        invalid: 'наднях',
        id: 147,
      },
      {
        valid: 'на дыбы',
        invalid: 'надыбы',
        id: 148,
      },
      {
        valid: 'назавтра',
        invalid: 'на завтра',
        id: 149,
      },
      {
        valid: 'назло',
        invalid: 'на зло',
        id: 150,
      },
      {
        valid: 'назубок',
        invalid: 'на зубок',
        id: 151,
      },
      {
        valid: 'на износ',
        invalid: 'наизнос',
        id: 152,
      },
      {
        valid: 'накануне',
        invalid: 'на кануне',
        id: 153,
      },
      {
        valid: 'на лету',
        invalid: 'налету',
        id: 154,
      },
      {
        valid: 'налицо',
        invalid: 'на лицо',
        id: 155,
      },
      {
        valid: 'на миг',
        invalid: 'намиг',
        id: 156,
      },
      {
        valid: 'на нет',
        invalid: 'нанет',
        id: 157,
      },
      {
        valid: 'на отлично',
        invalid: 'наотлично',
        id: 158,
      },
      {
        valid: 'наотмашь',
        invalid: 'на отмашь',
        id: 159,
      },
      {
        valid: 'на ощупь',
        invalid: 'наощупь',
        id: 160,
      },
      {
        valid: 'наперебой',
        invalid: 'на перебой',
        id: 161,
      },
      {
        valid: 'наперегонки',
        invalid: 'на перегонки',
        id: 162,
      },
      {
        valid: 'наперекор',
        invalid: 'на перекор',
        id: 163,
      },
      {
        valid: 'наперерыв',
        invalid: 'на перерыв',
        id: 164,
      },
      {
        valid: 'напоказ',
        invalid: 'на показ',
        id: 165,
      },
      {
        valid: 'наполовину',
        invalid: 'на половину',
        id: 166,
      },
      {
        valid: 'на полпути',
        invalid: 'на пол пути',
        id: 167,
      },
      {
        valid: 'напополам',
        invalid: 'на пополам',
        id: 168,
      },
      {
        valid: 'напрокат',
        invalid: 'на прокат',
        id: 169,
      },
      {
        valid: 'впросак',
        invalid: 'в просак',
        id: 170,
      },
      {
        valid: 'впятеро',
        invalid: 'в пятеро',
        id: 171,
      },
      {
        valid: 'вразбивку',
        invalid: 'в разбивку',
        id: 172,
      },
      {
        valid: 'вразброс',
        invalid: 'в разброс',
        id: 173,
      },
      {
        valid: 'вразрез',
        invalid: 'в разрез',
        id: 174,
      },
      {
        valid: 'на рысях',
        invalid: 'нарысях',
        id: 175,
      },
      {
        valid: 'на славу',
        invalid: 'наславу',
        id: 176,
      },
      {
        valid: 'насмерть (биться)',
        invalid: 'на смерть(биться)',
        id: 177,
      },
      {
        valid: 'на смех',
        invalid: 'насмех',
        id: 178,
      },
      {
        valid: 'натрое',
        invalid: 'на трое',
        id: 179,
      },
      {
        valid: 'не вправе',
        invalid: 'невправе',
        id: 180,
      },
      {
        valid: 'ненадолго',
        invalid: 'на надолго',
        id: 181,
      },
      {
        valid: 'не сегодня-завтра',
        invalid: 'не сегодня завтра',
        id: 182,
      },
      {
        valid: 'наудачу',
        invalid: 'на удачу',
        id: 183,
      },
      {
        valid: 'на ходу',
        invalid: 'находу',
        id: 184,
      },
      {
        valid: 'начеку',
        invalid: 'на чеку',
        id: 185,
      },
      {
        valid: 'наяву',
        invalid: 'на яву',
        id: 186,
      },
      {
        valid: 'недаром',
        invalid: 'не даром',
        id: 187,
      },
      {
        valid: 'нипочем',
        invalid: 'ни по чем',
        id: 188,
      },
      {
        valid: 'отроду (не видел)',
        invalid: 'от роду (не видел)',
        id: 189,
      },
      {
        valid: 'отчасти',
        invalid: 'от части',
        id: 190,
      },
      {
        valid: 'повсюду',
        invalid: 'по всюду',
        id: 191,
      },
      {
        valid: 'под конец',
        invalid: 'подконец',
        id: 192,
      },
      {
        valid: 'под мышки (взять)',
        invalid: 'подмышки (взять)',
        id: 193,
      },
      {
        valid: 'под стать',
        invalid: 'подстать',
        id: 194,
      },
      {
        valid: 'подчас',
        invalid: 'под час',
        id: 195,
      },
      {
        valid: 'позавчера',
        invalid: 'поза вчера',
        id: 196,
      },
      {
        valid: 'понаслышке',
        invalid: 'по наслышке',
        id: 197,
      },
      {
        valid: 'понемногу',
        invalid: 'по немногу',
        id: 198,
      },
      {
        valid: 'замужем',
        invalid: 'за мужем',
        id: 199,
      },
      {
        valid: 'запанибрата',
        invalid: 'за панибрата',
        id: 200,
      },
      {
        valid: 'извне',
        invalid: 'из вне',
        id: 201,
      },
      {
        valid: 'из-под мышек',
        invalid: 'из подмышек',
        id: 202,
      },
      {
        valid: 'исподтишка',
        invalid: 'из под тишка',
        id: 203,
      },
      {
        valid: 'посередине',
        invalid: 'по середине',
        id: 204,
      },
      {
        valid: 'посуху',
        invalid: 'по суху',
        id: 205,
      },
      {
        valid: 'сбоку',
        invalid: 'с боку',
        id: 206,
      },
      {
        valid: 'сверху донизу',
        invalid: 'с верху до низу',
        id: 207,
      },
      {
        valid: 'смолоду',
        invalid: 'с молоду',
        id: 208,
      },
      {
        valid: 'снизу доверху',
        invalid: 'с низу до верху',
        id: 209,
      },
      {
        valid: 'с разгона',
        invalid: 'сразгона',
        id: 210,
      },
      {
        valid: 'сряду',
        invalid: 'с ряду',
        id: 211,
      },
      {
        valid: 'чересчур',
        invalid: 'через чур',
        id: 212,
      },
    ],
  },

  'разряды союзов': {
    type: 'choice',
    inHeader: true,
    categories: [
      {
        category: 'Подчинительные',
        choiceWords: [
          'временной',
          'причинный',
          'целевой',
          'условный',
          'уступительный',
          'сравнительный',
          'следственный',
          'изъяснительный',
        ],
      },
      {
        category: 'Сочинительные',
        choiceWords: ['соединительный', 'противительный', 'разделительный'],
      },
    ],

    items: [
      {
        choiceWord: 'соединительный',
        word: 'и',
        id: 0,
      },
      {
        choiceWord: 'соединительный',
        word: 'также',
        id: 1,
      },
      {
        choiceWord: 'соединительный',
        word: 'тоже',
        id: 2,
      },
      {
        choiceWord: 'соединительный',
        word: 'ни…ни',
        id: 3,
      },
      {
        choiceWord: 'соединительный',
        word: 'не только…, но и',
        id: 4,
      },
      {
        choiceWord: 'соединительный',
        word: 'как…так и',
        id: 5,
      },
      {
        choiceWord: 'противительный',
        word: 'а',
        id: 6,
      },
      {
        choiceWord: 'противительный',
        word: 'но',
        id: 7,
      },
      {
        choiceWord: 'противительный',
        word: 'зато',
        id: 8,
      },
      {
        choiceWord: 'противительный',
        word: 'однако',
        id: 9,
      },
      {
        choiceWord: 'противительный',
        word: 'же',
        id: 10,
      },
      {
        choiceWord: 'разделительный',
        word: 'или',
        id: 11,
      },
      {
        choiceWord: 'разделительный',
        word: 'либо',
        id: 12,
      },
      {
        choiceWord: 'разделительный',
        word: 'то…то',
        id: 13,
      },
      {
        choiceWord: 'разделительный',
        word: 'не то…не то',
        id: 14,
      },
      {
        choiceWord: 'изъяснительный',
        word: 'что',
        id: 15,
      },
      {
        choiceWord: 'целевой',
        word: 'чтобы',
        id: 16,
      },
      {
        choiceWord: 'целевой',
        word: 'дабы',
        id: 17,
      },
      {
        choiceWord: 'временной',
        word: 'когда',
        id: 18,
      },
      {
        choiceWord: 'временной',
        word: 'лишь',
        id: 19,
      },
      {
        choiceWord: 'временной',
        word: 'пока',
        id: 20,
      },
      {
        choiceWord: 'временной',
        word: 'едва',
        id: 21,
      },
      {
        choiceWord: 'временной',
        word: 'прежде чем',
        id: 22,
      },
      {
        choiceWord: 'условный',
        word: 'если',
        id: 23,
      },
      {
        choiceWord: 'условный',
        word: 'раз',
        id: 24,
      },
      {
        choiceWord: 'условный',
        word: 'кабы',
        id: 25,
      },
      {
        choiceWord: 'сравнительный',
        word: 'как',
        id: 26,
      },
      {
        choiceWord: 'сравнительный',
        word: 'будто',
        id: 27,
      },
      {
        choiceWord: 'сравнительный',
        word: 'словно',
        id: 28,
      },
      {
        choiceWord: 'сравнительный',
        word: 'точно',
        id: 29,
      },
      {
        choiceWord: 'уступительный',
        word: 'несмотря на то что',
        id: 30,
      },
      {
        choiceWord: 'уступительный',
        word: 'хотя',
        id: 31,
      },
      {
        choiceWord: 'уступительный',
        word: 'пусть',
        id: 32,
      },
      {
        choiceWord: 'следствия',
        word: 'так что',
        id: 33,
      },
    ],
  },

  'разряды предлогов': {
    type: 'choice',
    inHeader: true,
    categories: [
      {
        choiceWords: [
          'объектный',
          'источник информации',
          'образа действия',
          'временной',
          'пространственный',
          'причинный',
          'целевой',
          'уступительный',
          'условный',
          'сравнительный',
        ],
      },
    ],

    items: [
      {
        choiceWord: 'объектный',
        word: 'о',
        id: 0,
      },
      {
        choiceWord: 'объектный',
        word: 'насчёт',
        id: 1,
      },
      {
        choiceWord: 'объектный',
        word: 'про',
        id: 2,
      },
      {
        choiceWord: 'объектный',
        word: 'по поводу',
        id: 3,
      },
      {
        choiceWord: 'источник информации',
        word: 'согласно',
        id: 4,
      },
      {
        choiceWord: 'источник информации',
        word: 'в соответствии с',
        id: 5,
      },
      {
        choiceWord: 'источник информации',
        word: 'на основе',
        id: 6,
      },
      {
        choiceWord: 'образа действия',
        word: 'посредством',
        id: 7,
      },
      {
        choiceWord: 'образа действия',
        word: 'за счёт',
        id: 8,
      },
      {
        choiceWord: 'образа действия',
        word: 'с помощью',
        id: 9,
      },
      {
        choiceWord: 'образа действия',
        word: 'при помощи',
        id: 10,
      },
      {
        choiceWord: 'временной',
        word: 'в течение',
        id: 11,
      },
      {
        choiceWord: 'временной',
        word: 'в продолжение',
        id: 12,
      },
      {
        choiceWord: 'временной',
        word: 'спустя',
        id: 13,
      },
      {
        choiceWord: 'временной',
        word: 'по мере',
        id: 14,
      },
      {
        choiceWord: 'пространственный',
        word: 'до',
        id: 15,
      },
      {
        choiceWord: 'пространственный',
        word: 'из',
        id: 16,
      },
      {
        choiceWord: 'пространственный',
        word: 'к',
        id: 17,
      },
      {
        choiceWord: 'пространственный',
        word: 'на',
        id: 18,
      },
      {
        choiceWord: 'пространственный',
        word: 'над',
        id: 19,
      },
      {
        choiceWord: 'пространственный',
        word: 'от',
        id: 20,
      },
      {
        choiceWord: 'пространственный',
        word: 'под',
        id: 21,
      },
      {
        choiceWord: 'пространственный',
        word: 'перед',
        id: 22,
      },
      {
        choiceWord: 'пространственный',
        word: 'у',
        id: 23,
      },
      {
        choiceWord: 'пространственный',
        word: 'через',
        id: 24,
      },
      {
        choiceWord: 'пространственный',
        word: 'сидеть (около) дома',
        id: 25,
      },
      {
        choiceWord: 'причинный',
        word: 'из-за',
        id: 26,
      },
      {
        choiceWord: 'причинный',
        word: 'ввиду',
        id: 27,
      },
      {
        choiceWord: 'причинный',
        word: 'вследствие',
        id: 28,
      },
      {
        choiceWord: 'причинный',
        word: 'по причине',
        id: 29,
      },
      {
        choiceWord: 'причинный',
        word: 'благодаря',
        id: 30,
      },
      {
        choiceWord: 'целевой',
        word: 'для',
        id: 31,
      },
      {
        choiceWord: 'целевой',
        word: 'за',
        id: 32,
      },
      {
        choiceWord: 'целевой',
        word: 'в целях',
        id: 33,
      },
      {
        choiceWord: 'уступительный',
        word: 'несмотря на',
        id: 34,
      },
      {
        choiceWord: 'уступительный',
        word: 'вопреки',
        id: 35,
      },
      {
        choiceWord: 'условный',
        word: 'при условии',
        id: 36,
      },
      {
        choiceWord: 'сравнительный',
        word: 'наподобие',
        id: 37,
      },
      {
        choiceWord: 'сравнительный',
        word: 'вроде',
        id: 38,
      },
      {
        choiceWord: 'сравнительный',
        word: 'в виде',
        id: 39,
      },
    ],
  },

  'разряды местоимений': {
    type: 'choice',
    inHeader: true,
    categories: [
      {
        choiceWords: [
          'личное',
          'притяжательное',
          'возвратное',
          'вопросительное',
          'относительное',
          'отрицательное',
          'неопределённое',
          'указательное',
          'определительное',
        ],
      },
    ],

    items: [
      {
        choiceWord: 'личное',
        word: 'я',
        id: 0,
      },
      {
        choiceWord: 'личное',
        word: 'ты',
        id: 1,
      },
      {
        choiceWord: 'личное',
        word: 'мы',
        id: 2,
      },
      {
        choiceWord: 'личное',
        word: 'вы',
        id: 3,
      },
      {
        choiceWord: 'личное',
        word: 'он',
        id: 4,
      },
      {
        choiceWord: 'личное',
        word: 'она',
        id: 5,
      },
      {
        choiceWord: 'личное',
        word: 'оно',
        id: 6,
      },
      {
        choiceWord: 'личное',
        word: 'они',
        id: 7,
      },
      {
        choiceWord: 'притяжательное',
        word: 'мой',
        id: 8,
      },
      {
        choiceWord: 'притяжательное',
        word: 'наш',
        id: 9,
      },
      {
        choiceWord: 'притяжательное',
        word: 'твой',
        id: 10,
      },
      {
        choiceWord: 'притяжательное',
        word: 'это (её) вещь',
        id: 11,
      },
      {
        choiceWord: 'притяжательное',
        word: 'свой',
        id: 12,
      },
      {
        choiceWord: 'притяжательное',
        word: 'это (его) вещь',
        id: 13,
      },
      {
        choiceWord: 'притяжательное',
        word: 'это (их) вещь',
        id: 14,
      },
      {
        choiceWord: 'возвратное',
        word: 'себя',
        id: 15,
      },
      {
        choiceWord: 'вопросительный',
        word: 'кто?',
        id: 16,
      },
      {
        choiceWord: 'вопросительный',
        word: 'что?',
        id: 17,
      },
      {
        choiceWord: 'вопросительный',
        word: 'какой?',
        id: 18,
      },
      {
        choiceWord: 'вопросительный',
        word: 'чей?',
        id: 19,
      },
      {
        choiceWord: 'вопросительный',
        word: 'сколько?',
        id: 20,
      },
      {
        choiceWord: 'вопросительный',
        word: 'каков?',
        id: 21,
      },
      {
        choiceWord: 'вопросительный',
        word: 'который?',
        id: 22,
      },
      {
        choiceWord: 'относительный',
        word: 'кто',
        id: 23,
      },
      {
        choiceWord: 'относительный',
        word: 'что',
        id: 24,
      },
      {
        choiceWord: 'относительный',
        word: 'какой',
        id: 25,
      },
      {
        choiceWord: 'относительный',
        word: 'чей',
        id: 26,
      },
      {
        choiceWord: 'относительный',
        word: 'сколько',
        id: 27,
      },
      {
        choiceWord: 'относительный',
        word: 'каков',
        id: 28,
      },
      {
        choiceWord: 'относительный',
        word: 'который',
        id: 29,
      },
      {
        choiceWord: 'отрицательное',
        word: 'никто',
        id: 30,
      },
      {
        choiceWord: 'отрицательное',
        word: 'ничто',
        id: 31,
      },
      {
        choiceWord: 'отрицательное',
        word: 'никакой',
        id: 32,
      },
      {
        choiceWord: 'отрицательное',
        word: 'ничей',
        id: 33,
      },
      {
        choiceWord: 'отрицательное',
        word: 'некого',
        id: 34,
      },
      {
        choiceWord: 'отрицательное',
        word: 'нечего',
        id: 35,
      },
      {
        choiceWord: 'неопределённое',
        word: 'некто',
        id: 36,
      },
      {
        choiceWord: 'неопределённое',
        word: 'нечто',
        id: 37,
      },
      {
        choiceWord: 'неопределённое',
        word: 'нисколько',
        id: 38,
      },
      {
        choiceWord: 'неопределённое',
        word: 'некоторый',
        id: 39,
      },
      {
        choiceWord: 'неопределённое',
        word: 'кое-кто',
        id: 40,
      },
      {
        choiceWord: 'неопределённое',
        word: 'что-то',
        id: 41,
      },
      {
        choiceWord: 'неопределённое',
        word: 'какой-нибудь',
        id: 42,
      },
      {
        choiceWord: 'неопределённое',
        word: 'чей-либо',
        id: 43,
      },
      {
        choiceWord: 'указательное',
        word: 'этот',
        id: 44,
      },
      {
        choiceWord: 'указательное',
        word: 'тот',
        id: 45,
      },
      {
        choiceWord: 'указательное',
        word: 'такой',
        id: 46,
      },
      {
        choiceWord: 'указательное',
        word: 'сей',
        id: 47,
      },
      {
        choiceWord: 'указательное',
        word: 'столько',
        id: 48,
      },
      {
        choiceWord: 'определительный',
        word: 'весь',
        id: 49,
      },
      {
        choiceWord: 'определительный',
        word: 'всякий',
        id: 50,
      },
      {
        choiceWord: 'определительный',
        word: 'каждый',
        id: 51,
      },
      {
        choiceWord: 'определительный',
        word: 'сам',
        id: 52,
      },
      {
        choiceWord: 'определительный',
        word: 'самый',
        id: 53,
      },
      {
        choiceWord: 'определительный',
        word: 'любой',
        id: 54,
      },
      {
        choiceWord: 'определительный',
        word: 'любой',
        id: 55,
      },
      {
        choiceWord: 'определительный',
        word: 'другой',
        id: 56,
      },
    ],
  },
};
