import { PrimaryWordsInterface } from '../types/types';

export const wordsForMorphologicalTests: PrimaryWordsInterface[] = [
  {
    valid: 'инструкторы',
    invalid: 'инструктора',
    id: 0,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'редакторы',
    invalid: 'редактора',
    id: 1,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'лекторы',
    invalid: 'лектора',
    id: 2,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'конструкторы',
    invalid: 'конструктора',
    id: 3,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'прожекторы',
    invalid: 'прожектора',
    id: 4,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'секторы',
    invalid: 'сектора',
    id: 5,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'инженеры',
    invalid: 'инженера',
    id: 6,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'шофёры',
    invalid: 'шофера',
    id: 7,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'бухгалтеры',
    invalid: 'бухгалтера',
    id: 8,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'диспетчеры',
    invalid: 'диспетчера',
    id: 9,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'договоры',
    invalid: 'договора',
    id: 10,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'драйверы',
    invalid: 'драйвера',
    id: 11,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'слесари',
    invalid: 'слесаря',
    id: 12,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'токари',
    invalid: 'токаря',
    id: 13,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'возрасты',
    invalid: 'возраста',
    id: 14,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'кремы',
    invalid: 'крема',
    id: 15,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'директора',
    invalid: 'директоры',
    id: 16,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'профессора',
    invalid: 'профессоры',
    id: 17,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'инспектора',
    invalid: 'инспекторы',
    id: 18,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'доктора',
    invalid: 'докторы',
    id: 19,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'катера',
    invalid: 'катеры',
    id: 20,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'ордера',
    invalid: 'ордеры',
    id: 21,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'тенора',
    invalid: 'теноры',
    id: 22,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'фельдшера',
    invalid: 'фельдшеры',
    id: 23,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'флюгера',
    invalid: 'флюгеры',
    id: 24,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'хутора',
    invalid: 'хуторы',
    id: 25,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'шулера',
    invalid: 'шулеры',
    id: 26,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'буфера',
    invalid: 'буферы',
    id: 27,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'веера',
    invalid: 'вееры',
    id: 28,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'повара',
    invalid: 'повары',
    id: 29,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'отпуска',
    invalid: 'отпуски',
    id: 30,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'паруса',
    invalid: 'парусы',
    id: 31,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'паспорта',
    invalid: 'паспорты',
    id: 32,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'погреба',
    invalid: 'погребы',
    id: 33,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.апельсинов',
    invalid: 'р.п.апельсин',
    id: 34,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'борта',
    invalid: 'борты',
    id: 35,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'черепа',
    invalid: 'черепы',
    id: 36,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.бананов',
    invalid: 'р.п.банан',
    id: 37,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.томатов',
    invalid: 'р.п.томат',
    id: 38,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.помидоров',
    invalid: 'р.п.помидор',
    id: 39,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.абрикосов',
    invalid: 'р.п.абрикос',
    id: 40,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.мандаринов',
    invalid: 'р.п.мандарин',
    id: 41,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.яблок',
    invalid: 'р.п.яблоков',
    id: 42,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.груш',
    invalid: 'р.п.грушей',
    id: 43,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.дынь',
    invalid: 'р.п.дыней',
    id: 44,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.казахов',
    invalid: 'р.п.казах',
    id: 45,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.калмыков',
    invalid: 'р.п.калмык',
    id: 46,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.киргизов',
    invalid: 'р.п.киргиз',
    id: 47,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.монголов',
    invalid: 'р.п.монгол',
    id: 48,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.армян',
    invalid: 'р.п.армянинов',
    id: 49,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.башкир',
    invalid: 'р.п.башкиров',
    id: 50,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.болгар',
    invalid: 'р.п.болгаров',
    id: 51,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'грузин',
    invalid: 'грузинов',
    id: 52,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'татар',
    invalid: 'татаров',
    id: 53,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.цыган',
    invalid: 'р.п.цыганов',
    id: 54,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.турок',
    invalid: 'р.п.турков',
    id: 55,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.бурят',
    invalid: 'р.п.бурятов',
    id: 56,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.байтов',
    invalid: 'р.п.байт',
    id: 57,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.гектаров',
    invalid: 'р.п.гектар',
    id: 58,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.грамов',
    invalid: 'р.п.грамм',
    id: 59,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.килограммов',
    invalid: 'р.п.килограмм',
    id: 60,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.ампер',
    invalid: 'р.п.амперов',
    id: 61,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.аршин',
    invalid: 'р.п.аршинов',
    id: 62,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.носков',
    invalid: 'р.п.носок',
    id: 63,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.гольфов',
    invalid: 'р.п.гольф',
    id: 64,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.рельсов',
    invalid: 'р.п.рельс',
    id: 65,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'джинсов',
    invalid: 'джинс',
    id: 66,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.бриджей',
    invalid: 'р.п.бридж',
    id: 67,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.ботинок',
    invalid: 'р.п.ботинков',
    id: 68,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.чулок',
    invalid: 'р.п.чулков',
    id: 69,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.шорт',
    invalid: 'р.п.шортов',
    id: 70,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.туфель',
    invalid: 'р.п.туфлей',
    id: 71,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.сапог',
    invalid: 'р.п.сапогов',
    id: 72,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.тапок',
    invalid: 'р.п.тапков',
    id: 73,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'тапок',
    invalid: 'тапка',
    id: 74,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.галош',
    invalid: 'р.п.галошей',
    id: 75,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.валенок',
    invalid: 'р.п.валенков',
    id: 76,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.серёг',
    invalid: 'р.п.серёжек',
    id: 77,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.солдат',
    invalid: 'р.п.солдатов',
    id: 78,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.гусар',
    invalid: 'р.п.гусаров',
    id: 79,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.кадет',
    invalid: 'р.п.кадетов',
    id: 80,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.партизан',
    invalid: 'р.п.партизанов',
    id: 81,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.яблонь',
    invalid: 'р.п.яблоней',
    id: 82,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.нянь',
    invalid: 'р.п.няней',
    id: 83,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.барышень',
    invalid: 'р.п.барышней',
    id: 84,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.кухонь',
    invalid: 'р.п.кухней',
    id: 85,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.басен',
    invalid: 'р.п.басней',
    id: 86,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.башен',
    invalid: 'р.п.башней',
    id: 87,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.вишен',
    invalid: 'р.п.вишней',
    id: 88,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.пашен',
    invalid: 'р.п.пашней',
    id: 89,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.спален',
    invalid: 'р.п.спальней',
    id: 90,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.мускулов',
    invalid: 'р.п.мускул',
    id: 91,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.чипсов',
    invalid: 'р.п.чипс',
    id: 92,
    trainerType: 'морфологические нормы',
  },
  {
    valid: 'р.п.макарон',
    invalid: 'р.п.макаронов',
    id: 93,
    trainerType: 'морфологические нормы',
  },
];
