import { PrimaryWordsInterface } from '../types/types';

export const wordsForNNTests: PrimaryWordsInterface[] = [
  {
    valid: 'бараний',
    invalid: 'баранний',
    id: 0,
    trainerType: 'н/нн',
  },
  {
    valid: 'багряный',
    invalid: 'багрянный',
    id: 1,
    trainerType: 'н/нн',
  },
  {
    valid: 'безветренный',
    invalid: 'безветреный',
    id: 2,
    trainerType: 'н/нн',
  },
  {
    valid: 'бесприданница',
    invalid: 'бесприданица',
    id: 3,
    trainerType: 'н/нн',
  },
  {
    valid: 'бессребреник',
    invalid: 'бессребренник',
    id: 4,
    trainerType: 'н/нн',
  },
  {
    valid: 'блаженный',
    invalid: 'блаженый',
    id: 5,
    trainerType: 'н/нн',
  },
  {
    valid: 'вареник',
    invalid: 'варенник',
    id: 6,
    trainerType: 'н/нн',
  },
  {
    valid: 'венчанный',
    invalid: 'венчаный',
    id: 7,
    trainerType: 'н/нн',
  },
  {
    valid: 'ветреный',
    invalid: 'ветренный',
    id: 8,
    trainerType: 'н/нн',
  },
  {
    valid: 'виденный',
    invalid: 'виденый',
    id: 9,
    trainerType: 'н/нн',
  },
  {
    valid: 'вороной',
    invalid: 'воронной',
    id: 10,
    trainerType: 'н/нн',
  },
  {
    valid: 'гостиная',
    invalid: 'гостинная',
    id: 11,
    trainerType: 'н/нн',
  },
  {
    valid: 'деревянный',
    invalid: 'деревяный',
    id: 12,
    trainerType: 'н/нн',
  },
  {
    valid: 'жданный',
    invalid: 'жданый',
    id: 13,
    trainerType: 'н/нн',
  },
  {
    valid: 'жёваный',
    invalid: 'жёванный',
    id: 14,
    trainerType: 'н/нн',
  },
  {
    valid: 'желанный',
    invalid: 'желаный',
    id: 15,
    trainerType: 'н/нн',
  },
  {
    valid: 'жеманный',
    invalid: 'жеманый',
    id: 16,
    trainerType: 'н/нн',
  },
  {
    valid: 'завещанный',
    invalid: 'завещаный',
    id: 17,
    trainerType: 'н/нн',
  },
  {
    valid: 'измождённый',
    invalid: 'измождёный',
    id: 18,
    trainerType: 'н/нн',
  },
  {
    valid: 'изысканный',
    invalid: 'изысканый',
    id: 19,
    trainerType: 'н/нн',
  },
  {
    valid: 'клёваный',
    invalid: 'клёванный',
    id: 20,
    trainerType: 'н/нн',
  },
  {
    valid: 'кованый',
    invalid: 'кованный',
    id: 21,
    trainerType: 'н/нн',
  },
  {
    valid: 'крещёный',
    invalid: 'крещённый',
    id: 22,
    trainerType: 'н/нн',
  },
  {
    valid: 'мудрёный',
    invalid: 'мудрённый',
    id: 23,
    trainerType: 'н/нн',
  },
  {
    valid: 'мученик',
    invalid: 'мученник',
    id: 24,
    trainerType: 'н/нн',
  },
  {
    valid: 'холстинный',
    invalid: 'холстиный',
    id: 25,
    trainerType: 'н/нн',
  },
  {
    valid: 'диковинный',
    invalid: 'диковиный',
    id: 26,
    trainerType: 'н/нн',
  },
  {
    valid: 'старинный',
    invalid: 'стариный',
    id: 27,
    trainerType: 'н/нн',
  },
  {
    valid: 'названыйбрат',
    invalid: 'названныйбрат',
    id: 28,
    trainerType: 'н/нн',
  },
  {
    valid: 'неведанный',
    invalid: 'неведаный',
    id: 29,
    trainerType: 'н/нн',
  },
  {
    valid: 'негаданный',
    invalid: 'негаданый',
    id: 30,
    trainerType: 'н/нн',
  },
  {
    valid: 'нежданный',
    invalid: 'нежданый',
    id: 31,
    trainerType: 'н/нн',
  },
  {
    valid: 'нежеланный',
    invalid: 'нежеланый',
    id: 32,
    trainerType: 'н/нн',
  },
  {
    valid: 'неожиданный',
    invalid: 'неожиданый',
    id: 33,
    trainerType: 'н/нн',
  },
  {
    valid: 'неслыханный',
    invalid: 'неслыханый',
    id: 34,
    trainerType: 'н/нн',
  },
  {
    valid: 'нечаянный',
    invalid: 'нечаяный',
    id: 35,
    trainerType: 'н/нн',
  },
  {
    valid: 'обезьяний',
    invalid: 'обезьянний',
    id: 36,
    trainerType: 'н/нн',
  },
  {
    valid: 'обещанный',
    invalid: 'обещаный',
    id: 37,
    trainerType: 'н/нн',
  },
  {
    valid: 'окаянный',
    invalid: 'окаяный',
    id: 38,
    trainerType: 'н/нн',
  },
  {
    valid: 'оловянный',
    invalid: 'оловяный',
    id: 39,
    trainerType: 'н/нн',
  },
  {
    valid: 'посажёныйотец',
    invalid: 'посажённыйотец',
    id: 40,
    trainerType: 'н/нн',
  },
  {
    valid: 'подлинный',
    invalid: 'подлиный',
    id: 41,
    trainerType: 'н/нн',
  },
  {
    valid: 'преданный',
    invalid: 'преданый',
    id: 42,
    trainerType: 'н/нн',
  },
  {
    valid: 'приданое',
    invalid: 'приданное',
    id: 43,
    trainerType: 'н/нн',
  },
  {
    valid: 'прощёноевоскресенье',
    invalid: 'прощённоевоскресенье',
    id: 44,
    trainerType: 'н/нн',
  },
  {
    valid: 'пряный',
    invalid: 'прянный',
    id: 45,
    trainerType: 'н/нн',
  },
  {
    valid: 'пудреница',
    invalid: 'пудренница',
    id: 46,
    trainerType: 'н/нн',
  },
  {
    valid: 'раненныйвбою',
    invalid: 'раненыйвбою',
    id: 47,
    trainerType: 'н/нн',
  },
  {
    valid: 'раненый',
    invalid: 'раненный',
    id: 48,
    trainerType: 'н/нн',
  },
  {
    valid: 'роженица',
    invalid: 'роженница',
    id: 49,
    trainerType: 'н/нн',
  },
  {
    valid: 'румяный',
    invalid: 'румянный',
    id: 50,
    trainerType: 'н/нн',
  },
  {
    valid: 'самонадеянный',
    invalid: 'самонадеяный',
    id: 51,
    trainerType: 'н/нн',
  },
  {
    valid: 'свиной',
    invalid: 'свинной',
    id: 52,
    trainerType: 'н/нн',
  },
  {
    valid: 'серебреник',
    invalid: 'серебренник',
    id: 53,
    trainerType: 'н/нн',
  },
  {
    valid: 'слышанный',
    invalid: 'слышаный',
    id: 54,
    trainerType: 'н/нн',
  },
  {
    valid: 'смышлёный',
    invalid: 'смышлённый',
    id: 55,
    trainerType: 'н/нн',
  },
  {
    valid: 'ставленник',
    invalid: 'ставленик',
    id: 56,
    trainerType: 'н/нн',
  },
  {
    valid: 'стеклянный',
    invalid: 'стекляный',
    id: 57,
    trainerType: 'н/нн',
  },
  {
    valid: 'суженый',
    invalid: 'суженный',
    id: 58,
    trainerType: 'н/нн',
  },
  {
    valid: 'труженик',
    invalid: 'труженник',
    id: 59,
    trainerType: 'н/нн',
  },
];
