import { PrimaryWordsInterface } from '../types/types';

export const wordsForPrePriTests: PrimaryWordsInterface[] = [
  {
    id: 0,
    valid: 'без прикрас',
    invalid: 'без прекрас',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 1,
    valid: 'беспристрастный',
    invalid: 'беспрестрастный',
    differenceIndexes: [5],
    trainerType: 'пре-при',
  },
  {
    id: 2,
    valid: 'придаточный',
    invalid: 'предаточный',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 3,
    valid: 'приобрёл',
    invalid: 'преобрёл',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 4,
    valid: 'приобщиться',
    invalid: 'преобщиться',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 5,
    valid: 'приобретение',
    invalid: 'преобретение',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 6,
    valid: 'придавать (значение)',
    invalid: 'предавать (значение)',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 7,
    valid: 'предавать (друга)',
    invalid: 'придавать (друга)',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 8,
    valid: 'приравнять',
    invalid: 'преравнять',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 9,
    valid: 'пристегнуть',
    invalid: 'престегнуть',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 10,
    valid: 'непримиримый',
    invalid: 'непремиримый',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 11,
    valid: 'призвание',
    invalid: 'презвание',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 12,
    valid: 'приноровиться',
    invalid: 'преноровиться',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 13,
    valid: 'принаряженный',
    invalid: 'пренаряженный',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 14,
    valid: 'пристроенный',
    invalid: 'престроенный',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 15,
    valid: 'пригорок',
    invalid: 'прегорок',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 16,
    valid: 'прикарманить',
    invalid: 'прекарманить',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 17,
    valid: 'прислушаться',
    invalid: 'преслушаться',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 18,
    valid: 'привратник',
    invalid: 'превратник',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 19,
    valid: 'преодолевать',
    invalid: 'приодолевать',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 20,
    valid: 'преобразование',
    invalid: 'приобразование',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 21,
    valid: 'президент',
    invalid: 'призидент',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 22,
    valid: 'прекрасный',
    invalid: 'прикрасный',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 23,
    valid: 'превозмочь',
    invalid: 'привозмочь',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 24,
    valid: 'превратить',
    invalid: 'привратить',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 25,
    valid: 'преграда',
    invalid: 'приграда',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 26,
    valid: 'превратности',
    invalid: 'привратности',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 27,
    valid: 'пререкаться',
    invalid: 'прирекаться',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 28,
    valid: 'преуспеть',
    invalid: 'приуспеть',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 29,
    valid: 'пресмыкаться',
    invalid: 'присмыкаться',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 30,
    valid: 'преследовать',
    invalid: 'приследовать',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 31,
    valid: 'преломление',
    invalid: 'приломление',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 32,
    valid: 'прекратить',
    invalid: 'прикратить',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 33,
    valid: 'преувеличивать',
    invalid: 'приувеличивать',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 34,
    valid: 'преодолеть',
    invalid: 'приодолеть',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 35,
    valid: 'превысить',
    invalid: 'привысить',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 36,
    valid: 'предание',
    invalid: 'придание',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 37,
    valid: 'преемственность',
    invalid: 'приемственность',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 38,
    valid: 'преобладать',
    invalid: 'приобладать',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 39,
    valid: 'преступник',
    invalid: 'приступник',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 40,
    valid: 'престижный',
    invalid: 'пристижный',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 41,
    valid: 'премудрый',
    invalid: 'примудрый',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 42,
    valid: 'превратный',
    invalid: 'привратный',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 43,
    valid: 'прекращение',
    invalid: 'прикращение',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 44,
    valid: 'преподаватель',
    invalid: 'приподаватель',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 45,
    valid: 'приглушить',
    invalid: 'преглушить',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 46,
    valid: 'приблизиться',
    invalid: 'преблизиться',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 47,
    valid: 'присоединить',
    invalid: 'пресоединить',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 48,
    valid: 'пребывать (дома)',
    invalid: 'прибывать (дома)',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 49,
    valid: 'прибывает (в столицу)',
    invalid: 'пребывает (в столицу)',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 50,
    valid: 'признать',
    invalid: 'презнать',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 51,
    valid: 'приготовить',
    invalid: 'преготовить',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 52,
    valid: 'приспособить',
    invalid: 'преспособить',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 53,
    valid: 'приближение',
    invalid: 'преближение',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 54,
    valid: 'привыкнуть',
    invalid: 'превыкнуть',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 55,
    valid: 'присмотреться',
    invalid: 'пресмотреться',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 56,
    valid: 'присоединение',
    invalid: 'пресоединение',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 57,
    valid: 'приблизительный',
    invalid: 'преблизительный',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 58,
    valid: 'пристанище',
    invalid: 'престанище',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 59,
    valid: 'причудливый',
    invalid: 'пречудливый',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 60,
    valid: 'привидение',
    invalid: 'превидение',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
  {
    id: 61,
    valid: 'приблизительно',
    invalid: 'преблизительно',
    differenceIndexes: [3],
    trainerType: 'пре-при',
  },
];
